"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowRight, Banknote, CircleDollarSign, CreditCard, GitCompareArrows, TrendingUp } from "lucide-react";
import { Card } from "@bbos/ui";
import { financeDemo } from "@/lib/finance-demo-data";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
const API = (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001/api") + "/finance";

export default function FinancePage() {
  const [data, setData] = React.useState(financeDemo);
  React.useEffect(() => { fetch(API + "/summary").then((response) => response.ok ? response.json() : null).then((result) => result && setData((current) => ({ ...current, ...result }))).catch(() => undefined); }, []);
  const cards = [["Caixa atual", money.format(data.cash), "/financeiro/fluxo-caixa", Banknote], ["Contas a receber", money.format(data.receivables), "/financeiro/receber", TrendingUp], ["Contas a pagar", money.format(data.payables), "/financeiro/pagar", CreditCard], ["Saldo projetado", money.format(data.projectedBalance), "/financeiro/fluxo-caixa", CircleDollarSign], ["Receita faturada", money.format(data.invoicedRevenue), "/vendas", TrendingUp], ["Resultado operacional projetado", money.format(data.operatingResult), "/custos", CircleDollarSign]] as const;
  return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-forest-700">Gestão financeira</p><h1 className="mt-2 text-3xl font-bold">Financeiro</h1><p className="mt-2 text-sm text-stone-500">Caixa, recebíveis, pagamentos e projeções gerenciais.</p></div><span className="rounded-full bg-amber-50 px-3 py-2 text-[10px] font-bold text-amber-800">Dados demonstrativos até conectar PostgreSQL</span></header><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{cards.map(([label, value, href, Icon]) => <Link key={label} href={href}><Card className="h-full p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-[11px] font-semibold text-stone-500">{label}</p><Icon size={15} className="text-forest-700"/></div><p className="mt-3 truncate text-xl font-bold">{value}</p></Card></Link>)}</section><section className="mt-6 grid gap-4 xl:grid-cols-[1.6fr_.8fr]"><CashChart/><Card className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-forest-700">Atenção financeira</p><h2 className="mt-1 text-lg font-bold">Indicadores operacionais</h2><div className="mt-5 space-y-4"><Alert label="Inadimplência em aberto" value={money.format(data.delinquency)} tone="danger"/><Alert label="A vencer nos próximos 7 dias" value={money.format(43200)} tone="warning"/><Alert label="Receita faturada ≠ caixa recebido" value="Conceito separado" tone="neutral"/></div><Link href="/financeiro/receber" className="mt-6 inline-flex items-center gap-1 text-xs font-bold text-forest-700">Ver contas a receber <ArrowRight size={13}/></Link></Card></section><section className="mt-6 grid gap-3 md:grid-cols-4"><Quick href="/financeiro/receber" title="Contas a receber" detail="A vencer, vencidos e pagamentos parciais"/><Quick href="/financeiro/pagar" title="Contas a pagar" detail="Fornecedores e centros de custo"/><Quick href="/financeiro/fluxo-caixa" title="Fluxo de caixa" detail="Realizado, projeção e movimentações"/><Quick href="/financeiro/conciliacao" title="Conciliação" detail="Compare movimentos e confirme divergências" icon={GitCompareArrows}/></section></div>;
}

function CashChart() { const series = [{ name: "Saldo de caixa", color: "#3E73A8", values: [238, 252, 247, 274, 291, 312] }, { name: "Entradas", color: "#16A06A", values: [44, 58, 62, 76, 82, 91] }, { name: "Saídas", color: "#C8923E", values: [39, 46, 51, 57, 63, 68] }, { name: "Caixa projetado", color: "#7867A9", values: [312, 328, 349, 377, 421, 478] }]; const x = (i: number) => 35 + i * 98; const y = (v: number) => 190 - v / 3; const points = (values: number[]) => values.map((v, i) => String(x(i)) + "," + String(y(v))).join(" "); return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-forest-700">Fluxo de Caixa</p><h2 className="mt-1 text-lg font-bold">Realizado e Projetado</h2></div><Link href="/financeiro/fluxo-caixa" className="text-xs font-bold text-forest-700">Detalhar</Link></div><svg viewBox="0 0 620 220" className="mt-5 h-[240px] w-full">{[0, 100, 200, 300, 400].map((v) => <g key={v}><line x1="35" x2="585" y1={y(v)} y2={y(v)} stroke="#D8E1DE"/><text x="28" y={y(v)+4} textAnchor="end" fontSize="10" fill="#626B69">{v}k</text></g>)}{series.map((item) => <polyline key={item.name} points={points(item.values)} fill="none" stroke={item.color} strokeWidth="2.5" strokeDasharray={item.name === "Caixa projetado" ? "6 5" : undefined} strokeLinecap="round"/>)}</svg><div className="mt-2 flex flex-wrap gap-4">{series.map((item) => <span key={item.name} className="flex items-center gap-2 text-[10px] text-stone-600"><i className="size-2 rounded-full" style={{ background: item.color }}/>{item.name}</span>)}</div></Card>; }
function Alert({ label, value, tone }: { label: string; value: string; tone: string }) { return <div className="flex items-center justify-between border-b border-stone-100 pb-3"><p className="text-xs text-stone-500">{label}</p><strong className={tone === "danger" ? "text-xs text-red-700" : tone === "warning" ? "text-xs text-amber-700" : "text-xs text-stone-700"}>{value}</strong></div>; }
function Quick({ href, title, detail, icon: Icon = ArrowRight }: { href: string; title: string; detail: string; icon?: typeof ArrowRight }) { return <Link href={href}><Card className="p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><h3 className="text-sm font-bold">{title}</h3><Icon size={14} className="text-stone-400"/></div><p className="mt-2 text-xs text-stone-500">{detail}</p></Card></Link>; }
