"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import styles from "./page.module.css";
type Item={id:string;name:string;image:string;color:string};type Family=Item&{items:Item[]};
const R="https://raw.githubusercontent.com/rezendeantonio1410-ops/bbos/staging/cupping-mobile-v2/apps/web/public";const I=(id:string,name:string,path:string,color:string):Item=>({id,name,image:R+path,color});
const families:Family[]=[{...I("fruit","Frutado","/sensory/aroma/frutado/frutas-vermelhas/morango.webp","#d94b52"),items:[I("strawberry","Morango","/sensory/aroma/frutado/frutas-vermelhas/morango.webp","#d94b52"),I("cherry","Cereja","/sensory/aroma/frutado/frutas-vermelhas/cereja.webp","#b72f3d"),I("raspberry","Framboesa","/sensory/aroma/frutado/frutas-vermelhas/framboesa.webp","#c7445c"),I("tangerine","Tangerina","/sensory/aroma/frutado/citricos/tangerina.webp","#ed8a2b"),I("mango","Manga","/sensory/aroma/frutado/tropicais/manga.png","#e7a53b")]},{...I("sweet","Doce","/sensory/aroma/doce/acucares-caramelizados/caramelo.webp","#c97b35"),items:[I("caramel","Caramelo","/sensory/aroma/doce/acucares-caramelizados/caramelo.webp","#c97b35"),I("sugar","Açúcar mascavo","/sensory/aroma/doce/acucares-caramelizados/acucar-mascavo.png","#a76b3c"),I("honey","Mel","/sensory/aroma/doce/acucares-caramelizados/mel.webp","#d9a52e"),I("dulce","Doce de leite","/sensory/aroma/doce/confeitaria/doce-de-leite.png","#d6a05b")]},{...I("cocoa","Chocolate / Cacau","/sensory/aroma/tostado/cacau-chocolate/chocolate-amargo.webp","#79503d"),items:[I("cocoa-note","Cacau","/sensory/aroma/tostado/cacau-chocolate/cacau.png","#684335"),I("dark","Chocolate amargo","/sensory/aroma/tostado/cacau-chocolate/chocolate-amargo.webp","#5d3c31"),I("hazelnut","Avelã","/sensory/aroma/tostado/nozes/avela-torrada.webp","#9a7050"),I("almond","Amêndoa","/sensory/aroma/tostado/nozes/amendoa-torrada.png","#b18461")]},{...I("floral","Floral","/sensory/aroma/floral/flores-brancas/jasmim.webp","#b96b9d"),items:[I("jasmine","Jasmim","/sensory/aroma/floral/flores-brancas/jasmim.webp","#b96b9d"),I("orange-flower","Flor de laranjeira","/sensory/aroma/floral/flores-brancas/flor-de-laranjeira.webp","#d99c79"),I("coffee-flower","Flor de café","/sensory/aroma/floral/flores-brancas/flor-de-cafe.webp","#b98aa5")]}];
const acids=["Macio","Equilibrado","Cítrico 🍊","Málico 🍏","Vivo ✦"];
const products={fruit:["Singular","ÉPICOS","R$ 85","Frutado · Complexo · Evolutivo"],sweet:["Caramelo","CLÁSSICOS","R$ 68","Caramelo · Chocolate · Conforto"],cocoa:["Caramelo","CLÁSSICOS","R$ 68","Chocolate · Caramelo · Envolvente"],floral:["Microlote Raro","RAROS","R$ 53","Floral · Delicado · Memorável"]} as const;
export default function Page(){const[step,setStep]=useState<"family"|"items"|"acid"|"result">("family");const[fid,setFid]=useState("fruit");const[selected,setSelected]=useState<string[]>([]);const[acid,setAcid]=useState("");const family=families.find(x=>x.id===fid)!;const p=products[fid as keyof typeof products];const toggle=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);if(step==="result")return <main className={styles.page}><Header/><section className={styles.resultPage}><div className={styles.resultLead}><p>ACHEI.</p><h1>Eu escolheria este para você.</h1></div><article className={styles.recommendation} style={{"--tone":family.color} as React.CSSProperties}><div className={styles.resultBag}><span>BISPO</span><i/></div><div className={styles.resultCopy}><p>{p[1]}</p><h2>{p[0]}</h2><strong>{p[3]}</strong><span>Sua xícara: {family.items.filter(x=>selected.includes(x.id)).map(x=>x.name).join(" · ")}</span><div className={styles.resultBuy}><b>{p[2]} <small>· pacote</small></b><button>Quero experimentar →</button></div><button className={styles.why} onClick={()=>{setSelected([]);setAcid("");setStep("family")}}>Explorar de novo</button></div></article></section></main>;
return <main className={styles.page}><Header/><section className={styles.experience}><div className={styles.intro}><p>BISPO · VAMOS DESCOBRIR JUNTOS</p><h1>{step==="family"?"O que dá vontade?":step==="items"?`Que tipo de ${family.name.toLowerCase()} chama você?`:"E o frescor?"}</h1><span>{step==="family"?"Toque em uma parte da roda. A escolha já abre o próximo caminho.":step==="items"?"Escolha pelas imagens. Elas entram na sua xícara.":"Pense na sensação: mais macio ou mais vivo?"}</span></div><div className={styles.journeyStage}>{step==="family"&&<div className={styles.familyWheel}><div className={styles.wheelCore}><strong>SUA XÍCARA</strong><small>toque e explore</small></div>{families.map((f,i)=><button key={f.id} className={`${styles.wheelSector} ${styles[`sector${i}`]}`} style={{"--tone":f.color} as React.CSSProperties} onClick={()=>{setFid(f.id);setSelected([]);setStep("items")}} aria-label={`Explorar ${f.name}`}><img src={f.image} alt=""/><span>{f.name}</span></button>)}</div>}{step==="items"&&<><button className={styles.why} onClick={()=>setStep("family")}>← voltar à roda</button><div className={styles.descriptorGrid}>{family.items.map(x=><button key={x.id} className={`${styles.descriptorTile} ${selected.includes(x.id)?styles.selected:""}`} style={{"--tone":x.color} as React.CSSProperties} onClick={()=>toggle(x.id)}><span><img src={x.image} alt={x.name}/>{selected.includes(x.id)&&<i>✓</i>}</span><strong>{x.name}</strong></button>)}</div></>}{step==="acid"&&<div className={styles.choiceGrid}>{acids.map(x=><button key={x} className={`${styles.choiceCard} ${acid===x?styles.selected:""}`} onClick={()=>setAcid(x)}><strong>{x}</strong></button>)}</div>}</div>{selected.length>0&&<div className={styles.memoryTrail}><small>SUA XÍCARA</small>{family.items.filter(x=>selected.includes(x.id)).map(x=><span key={x.id}>{x.name}</span>)}</div>}<div className={styles.bispoWhisper}><strong>Bispo</strong><span>{step==="family"?"Escolha pelo desejo. Eu traduzo o resto.":step==="items"?"Boa. Sua xícara está tomando forma.":acid?`Entendi: ${acid.toLowerCase()}. Agora já consigo escolher um café para você.`:"Toque na sensação que mais combina com você."}</span></div><div className={styles.mobileNav}>{step==="items"&&<button className={styles.continueButton} disabled={!selected.length} onClick={()=>setStep("acid")}>Minha xícara →</button>}{step==="acid"&&<button className={styles.continueButton} disabled={!acid} onClick={()=>setStep("result")}>Descobrir meu café →</button>}</div></section></main>}
function Header(){return <header className={styles.header}><Link href="/loja" className={styles.brand}><Image src="/brand/logo/bispo-logo-official-transparent.png" width={150} height={50} alt="Bispo Coffees" priority/></Link><div className={styles.headerCopy}><span>DESCUBRA O SEU CAFÉ</span></div><Link className={styles.close} href="/loja">×</Link></header>}
