"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import type {CSSProperties,ReactNode} from "react";
import styles from "./page.module.css";

const R="https://raw.githubusercontent.com/rezendeantonio1410-ops/bbos/staging/cupping-mobile-v2/apps/web/public";
const img=(p:string)=>R+p;
const data:any[]=[
{id:"fruit",name:"Frutado",color:"#d94b52",image:img("/sensory/aroma/frutado/frutas-vermelhas/morango.webp"),subs:[
{id:"red",name:"Frutas vermelhas",color:"#c73f51",image:img("/sensory/aroma/frutado/frutas-vermelhas/cereja.webp"),d:[{id:"strawberry",name:"Morango",image:img("/sensory/aroma/frutado/frutas-vermelhas/morango.webp")},{id:"cherry",name:"Cereja",image:img("/sensory/aroma/frutado/frutas-vermelhas/cereja.webp")},{id:"raspberry",name:"Framboesa",image:img("/sensory/aroma/frutado/frutas-vermelhas/framboesa.webp")}]},
{id:"citrus",name:"Cítricos",color:"#e6902e",image:img("/sensory/aroma/frutado/citricos/tangerina.webp"),d:[{id:"tangerine",name:"Tangerina",image:img("/sensory/aroma/frutado/citricos/tangerina.webp")},{id:"lemon",name:"Limão",image:img("/sensory/aroma/frutado/citricos/limao.webp")},{id:"bergamot",name:"Bergamota",image:img("/sensory/aroma/frutado/citricos/bergamota.webp")}]}]},
{id:"sweet",name:"Doce",color:"#c97b35",image:img("/sensory/aroma/doce/acucares-caramelizados/caramelo.webp"),subs:[
{id:"caramelized",name:"Caramelizados",color:"#c97b35",image:img("/sensory/aroma/doce/acucares-caramelizados/caramelo.webp"),d:[{id:"caramel",name:"Caramelo",image:img("/sensory/aroma/doce/acucares-caramelizados/caramelo.webp")},{id:"honey",name:"Mel",image:img("/sensory/aroma/doce/acucares-caramelizados/mel.webp")},{id:"brown-sugar",name:"Açúcar mascavo",image:img("/sensory/aroma/doce/acucares-caramelizados/acucar-mascavo.png")}]},
{id:"confectionery",name:"Confeitaria",color:"#d6a05b",image:img("/sensory/aroma/doce/confeitaria/doce-de-leite.png"),d:[{id:"dulce",name:"Doce de leite",image:img("/sensory/aroma/doce/confeitaria/doce-de-leite.png")},{id:"vanilla",name:"Baunilha",image:img("/sensory/aroma/doce/confeitaria/baunilha.png")},{id:"toffee",name:"Toffee",image:img("/sensory/aroma/doce/confeitaria/toffee.png")}]}]},
{id:"cocoa",name:"Chocolate / Cacau",color:"#79503d",image:img("/sensory/aroma/tostado/cacau-chocolate/chocolate-amargo.webp"),subs:[
{id:"chocolate",name:"Chocolate",color:"#684335",image:img("/sensory/aroma/tostado/cacau-chocolate/chocolate-amargo.webp"),d:[{id:"cocoa-note",name:"Cacau",image:img("/sensory/aroma/tostado/cacau-chocolate/cacau.png")},{id:"dark",name:"Chocolate amargo",image:img("/sensory/aroma/tostado/cacau-chocolate/chocolate-amargo.webp")},{id:"milk",name:"Chocolate ao leite",image:img("/sensory/aroma/tostado/cacau-chocolate/chocolate-ao-leite.png")}]},
{id:"nuts",name:"Castanhas",color:"#9a7050",image:img("/sensory/aroma/tostado/nozes/avela-torrada.webp"),d:[{id:"hazelnut",name:"Avelã",image:img("/sensory/aroma/tostado/nozes/avela-torrada.webp")},{id:"almond",name:"Amêndoa",image:img("/sensory/aroma/tostado/nozes/amendoa-torrada.png")},{id:"walnut",name:"Noz",image:img("/sensory/aroma/tostado/nozes/noz.png")}]}]},
{id:"floral",name:"Floral",color:"#b96b9d",image:img("/sensory/aroma/floral/flores-brancas/jasmim.webp"),subs:[
{id:"white",name:"Flores brancas",color:"#b96b9d",image:img("/sensory/aroma/floral/flores-brancas/jasmim.webp"),d:[{id:"jasmine",name:"Jasmim",image:img("/sensory/aroma/floral/flores-brancas/jasmim.webp")},{id:"orange-flower",name:"Flor de laranjeira",image:img("/sensory/aroma/floral/flores-brancas/flor-de-laranjeira.webp")},{id:"coffee-flower",name:"Flor de café",image:img("/sensory/aroma/floral/flores-brancas/flor-de-cafe.webp")}]},
{id:"perfumed",name:"Flores perfumadas",color:"#aa6a91",image:img("/sensory/aroma/floral/flores-perfumadas/rosa.png"),d:[{id:"rose",name:"Rosa",image:img("/sensory/aroma/floral/flores-perfumadas/rosa.png")},{id:"lavender",name:"Lavanda",image:img("/sensory/aroma/floral/flores-perfumadas/lavanda.png")},{id:"violet",name:"Violeta",image:img("/sensory/aroma/floral/flores-perfumadas/violeta.png")}]}]}
];
const acids=[{id:"soft",name:"Macio",hint:"suave e confortável",color:"#eadfc8"},{id:"balanced",name:"Equilibrado",hint:"frescor na medida",color:"#efd39c"},{id:"fresh",name:"Fresco",hint:"como laranja",color:"#efad58"},{id:"juicy",name:"Suculento",hint:"como maçã",color:"#b8cc78"},{id:"alive",name:"Vivo",hint:"mais energia",color:"#88aa63"}];
const products:any={fruit:["Singular","ÉPICOS","R$ 84","≈ R$ 3,36/xícara","Frutado · Complexo · Evolutivo"],sweet:["Caramelo","CLÁSSICOS","R$ 68","≈ R$ 2,72/xícara","Caramelo · Chocolate · Conforto"],cocoa:["Caramelo","CLÁSSICOS","R$ 68","≈ R$ 2,72/xícara","Chocolate · Caramelo · Envolvente"],floral:["Microlote Raro","RAROS","R$ 54","≈ R$ 4,32/xícara","Floral · Delicado · Memorável"]};

export default function Page(){
 const[phase,setPhase]=useState("aroma-family"),[af,setAf]=useState(""),[as,setAs]=useState(""),[ad,setAd]=useState<string[]>([]),[ff,setFf]=useState(""),[fs,setFs]=useState(""),[fd,setFd]=useState<string[]>([]),[acid,setAcid]=useState("");
 const isFlavor=phase.startsWith("flavor"); const famId=isFlavor?ff:af; const subId=isFlavor?fs:as; const fam=data.find(x=>x.id===famId); const sub=fam?.subs.find((x:any)=>x.id===subId);
 const names=(ids:string[])=>data.flatMap(x=>x.subs.flatMap((s:any)=>s.d)).filter((x:any)=>ids.includes(x.id)).map((x:any)=>x.name);
 const score:any={fruit:0,sweet:0,cocoa:0,floral:0}; if(score[af]!==undefined)score[af]+=2;if(score[ff]!==undefined)score[ff]+=2; const dominant=Object.keys(score).sort((a,b)=>score[b]-score[a])[0]||"fruit"; const acidName=acids.find(x=>x.id===acid)?.name||"Equilibrado"; const p=products[dominant];
 const profile=dominant==="fruit"?`frutado, aromático e ${acidName.toLowerCase()}`:dominant==="sweet"?`doce, confortável e ${acidName.toLowerCase()}`:dominant==="cocoa"?`profundo, envolvente e ${acidName.toLowerCase()}`:`floral, delicado e ${acidName.toLowerCase()}`;
 const chooseFamily=(id:string)=>{if(isFlavor){setFf(id);setFs("");setFd([]);setPhase("flavor-sub")}else{setAf(id);setAs("");setAd([]);setPhase("aroma-sub")}};
 const chooseSub=(id:string)=>{if(isFlavor){setFs(id);setPhase("flavor-desc")}else{setAs(id);setPhase("aroma-desc")}};
 const chooseDesc=(id:string)=>{if(isFlavor){const v=fd.includes(id)?fd.filter(x=>x!==id):[...fd,id].slice(-2);setFd(v);if(v.length===2)setTimeout(()=>setPhase("acid"),360)}else{const v=ad.includes(id)?ad.filter(x=>x!==id):[...ad,id].slice(-2);setAd(v);if(v.length===2)setTimeout(()=>setPhase("flavor-family"),360)}};
 const backMap:any={"aroma-family":"aroma-family","aroma-sub":"aroma-family","aroma-desc":"aroma-sub","flavor-family":"aroma-desc","flavor-sub":"flavor-family","flavor-desc":"flavor-sub","acid":"flavor-desc"};
 if(phase==="profile")return <Shell><section className={`${styles.resultScene} ${styles[dominant]}`}><div className={styles.quizReveal}><small>ACHO QUE ENTENDI VOCÊ.</small><h1>Hoje, sua xícara pede...</h1><div className={styles.profileWords}><b>{profile}</b></div><p>Você escolheu pelo impulso, confirmou no sabor e mostrou quanto de frescor queria sentir.</p><div className={styles.summary}><span>AROMA · {names(ad).join(" + ")}</span><span>SABOR · {names(fd).join(" + ")}</span><span>FRESCOR · {acidName}</span></div><button className={styles.humanCta} onClick={()=>setPhase("desire")}>Quero imaginar essa xícara</button></div></section></Shell>;
 if(phase==="desire")return <Shell><section className={`${styles.desireScene} ${styles[dominant]}`}><div className={styles.cupWorld}><div className={styles.steam}/><div className={styles.cup}/><div className={styles.sensoryCloud}>{[...names(ad),...names(fd)].slice(0,4).map((x:string)=><span key={x}>{x}</span>)}</div></div><div className={styles.desireCopy}><small>IMAGINE O PRIMEIRO GOLE.</small><h1>{dominant==="fruit"?"Fruta primeiro. Doçura junto. Frescor no final.":dominant==="sweet"?"Doçura que chega cedo. Conforto que fica.":dominant==="cocoa"?"Aroma profundo. Textura envolvente. Final longo.":"Aroma que sobe. Delicadeza no gole. Frescor que permanece."}</h1><p>Essa é a direção sensorial que suas escolhas construíram hoje.</p><div className={styles.bispoVoice}><b>Bispo</b><span>Agora eu tenho um café em mente para você.</span></div><button className={styles.humanCta} onClick={()=>setPhase("product")}>Quero conhecer esse café</button></div></section></Shell>;
 if(phase==="product")return <Shell><section className={styles.productScene}><div className={styles.productIntro}><small>SE EU ESTIVESSE ESCOLHENDO PARA VOCÊ HOJE...</small><h1>Eu começaria por este.</h1></div><article className={styles.productCard}><div><small>{p[1]}</small><h2>{p[0]}</h2><strong>{p[4]}</strong><p>Ele segue a direção que você construiu nesta sessão. Amanhã você pode descobrir outro lado do seu paladar.</p></div><div className={styles.price}><b>{p[2]} <small>· pacote</small></b><span>{p[3]}</span><button>Quero provar esse</button></div></article><div className={styles.feedback}><b>Bispo</b><span>Cheguei perto do que você gosta?</span><div><button>Sim, é por aí</button><button onClick={()=>location.reload()}>Quero descobrir outro lado meu</button></div></div></section></Shell>;
 const title=phase==="aroma-family"?"O que chama você no aroma?":phase==="aroma-sub"?`Dentro de ${fam?.name.toLowerCase()}, para onde você iria?`:phase==="aroma-desc"?"Escolha dois que mexem com você.":phase==="flavor-family"?"Agora imagine o primeiro gole.":phase==="flavor-sub"?"No sabor, que caminho combina mais?":phase==="flavor-desc"?"Escolha dois sabores que você procuraria.":"Só mais uma coisa: o frescor.";
 const selected=isFlavor?fd:ad;
 return <Shell><section className={styles.experience}>{phase!=="aroma-family"&&<button className={styles.back} onClick={()=>setPhase(backMap[phase]||"aroma-family")}>← quero rever</button>}<div className={styles.intro}><p>{phase.startsWith("aroma")?"AROMA":phase.startsWith("flavor")?"SABOR":"ACIDEZ"} · BISPO VAI COM VOCÊ</p><h1>{title}</h1><span>{phase.endsWith("family")?"Um toque basta. Escolha pelo primeiro impulso.":phase.endsWith("sub")?"Toque no caminho que mais te atrai.":phase.endsWith("desc")?"Não pense demais. Os dois primeiros costumam dizer bastante.":"Toque na sensação que combina com a xícara que você imaginou."}</span></div><div className={styles.journeyStage}>{phase.endsWith("family")&&<Wheel items={data} pick={chooseFamily}/>} {phase.endsWith("sub")&&fam&&<Wheel items={fam.subs} pick={chooseSub}/>} {phase.endsWith("desc")&&sub&&<div className={styles.descriptorGrid}>{sub.d.map((x:any)=>{const on=selected.includes(x.id);return <button key={x.id} className={`${styles.descriptorTile} ${on?styles.selected:""}`} style={{"--tone":fam.color} as CSSProperties} onClick={()=>chooseDesc(x.id)}><span><img src={x.image} alt={x.name}/>{on&&<i>✓</i>}</span><strong>{x.name}</strong></button>})}</div>} {phase==="acid"&&<div className={styles.acidMandala}><div className={styles.acidCore}><strong>SUA XÍCARA</strong><small>toque no frescor</small></div>{acids.map((x,i)=><button key={x.id} className={styles.acidPetal} style={{"--tone":x.color,"--i":i} as CSSProperties} onClick={()=>{setAcid(x.id);setTimeout(()=>setPhase("profile"),300)}}><b>{x.name}</b><span>{x.hint}</span></button>)}</div>}</div><Trail a={names(ad)} f={names(fd)}/><div className={styles.bispoWhisper}><strong>Bispo</strong><span>{phase==="aroma-family"?"Comece pelo que puxou seu olhar.":phase.endsWith("desc")&&selected.length?`${names(selected).join(" com ")}... boa pista.`:phase==="acid"?"Escolha pela sensação, não pela teoria.":"Boa. Vamos chegar um pouco mais perto."}</span></div></section></Shell>}
function Wheel({items,pick}:{items:any[];pick:(id:string)=>void}){return <div className={styles.familyWheel}><div className={styles.wheelCore}><strong>SUA XÍCARA</strong><small>toque e explore</small></div>{items.slice(0,4).map((x:any,i:number)=><button key={x.id} className={`${styles.wheelSector} ${styles[`sector${i}`]}`} style={{"--tone":x.color} as CSSProperties} onClick={()=>pick(x.id)}><img src={x.image} alt=""/><span>{x.name}</span></button>)}</div>}
function Trail({a,f}:{a:string[];f:string[]}){if(!a.length&&!f.length)return null;return <div className={styles.memoryTrail}><small>SUA XÍCARA</small>{a.map(x=><span key={"a"+x}>{x}</span>)}{f.map(x=><span key={"f"+x}>{x}</span>)}</div>}
function Shell({children}:{children:ReactNode}){return <main className={styles.page}><header className={styles.header}><Link href="/loja" className={styles.brand}><Image src="/brand/logo/bispo-logo-official-transparent.png" width={150} height={50} alt="Bispo Coffees" priority/></Link><div className={styles.headerCopy}><span>DESCUBRA O SEU CAFÉ</span></div><Link className={styles.close} href="/loja">×</Link></header>{children}</main>}
