"use client";
import * as React from "react";
import Link from "next/link";
import { BarChart3 } from "lucide-react";
import { currentUser } from "@/lib/current-user";
import { salesDesktopRoutes as routes } from "@/lib/sales-routes";
import { SalesEmptyState, SalesKpi, SalesPageHeader } from "@/components/sales-components";
const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001/api";
type Reports = { revenue: number; orders: number; averageTicket: number; customers: number; products: Array<{ product: string; sku: string; units: number; revenue: number }>; recentOrders: Array<{ id: string; orderNumber: string; customer: string; total: number; status: string }> };
const empty: Reports = { revenue: 0, orders: 0, averageTicket: 0, customers: 0, products: [], recentOrders: [] };
const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
export default function SalesReportsPage() { const [data, setData] = React.useState<Reports>(empty); React.useEffect(() => { fetch(`${API}/commercial/representative-reports`, { headers: { "x-user-id": currentUser.id } }).then((r) => r.ok ? r.json() : null).then((value) => value && setData(value)).catch(() => undefined); }, []); const hasSales = data.revenue > 0 || data.orders > 0; return <main className="min-h-screen bg-[#F7F7F5] px-5 py-7"><div className="mx-auto max-w-7xl"><SalesPageHeader title="Meu desempenho" description="Acompanhe sua evolução comercial e compare resultados com suas metas." /><section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SalesKpi label="Vendas" value={money(data.revenue)} tone="info"/><SalesKpi label="Pedidos" value={data.orders} tone="info"/><SalesKpi label="Ticket médio" value={money(data.averageTicket)} tone="success"/><SalesKpi label="Clientes" value={data.customers} tone="neutral"/></section>{hasSales ? <><section className="mt-5 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><BarChart3 size={18} className="text-blue-700"/> Vendas por produto</h2><div className="mt-4 grid gap-2 md:grid-cols-2">{data.products.map((item) => <Link key={item.sku} href={routes.catalog} className="flex items-center justify-between rounded-xl border border-stone-100 p-3 text-sm transition hover:bg-stone-50"><div><strong>{item.product}</strong><p className="text-xs text-stone-500">{item.sku} · {item.units} unidades</p></div><strong>{money(item.revenue)}</strong></Link>)}</div></section>{data.recentOrders.length > 0 && <section className="mt-5 rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Pedidos recentes</h2><div className="mt-4 space-y-2">{data.recentOrders.map((item) => <Link key={item.id} href={`${routes.orders}/${item.id}`} className="flex items-center justify-between border-b border-stone-100 py-3 text-sm transition hover:bg-stone-50"><span><strong>{item.orderNumber}</strong><span className="ml-2 text-stone-500">{item.customer}</span></span><span className="font-semibold">{money(item.total)}</span></Link>)}</div></section>}</> : <div className="mt-5"><SalesEmptyState title="Ainda não há vendas neste período." description="Quando você começar a registrar pedidos, seu desempenho aparecerá aqui." primaryAction={{ label: "Criar pedido", href: routes.newOrder }} secondaryAction={{ label: "Cadastrar cliente", href: routes.newClient }} /></div>}</div></main>; }
