"use client";

import { useEffect, useMemo, useState } from "react";
import { FlaskConical, Save, ArrowRight, CheckCircle2, QrCode } from "lucide-react";
import { ActionBar, Badge, Button, Card, HumanEmptyState, HumanPageHeader, StatusBadge } from "@bbos/ui";
import { getApiBaseUrl } from "@/lib/api-url";

const API = `${getApiBaseUrl()}/cupping`;
const fields = ["fragrance", "flavor", "aftertaste", "acidity", "body", "uniformity", "balance", "cleanCup", "sweetness", "overall"] as const;
const labels: Record<(typeof fields)[number], string> = { fragrance: "Aroma", flavor: "Flavor", aftertaste: "Finalização", acidity: "Acidez", body: "Corpo", uniformity: "Uniformidade", balance: "Equilíbrio", cleanCup: "Clean cup", sweetness: "Doçura", overall: "Overall" };
type Session = { id: string; code: string; status: string; decision?: string | null; protocol: string; sample: { sampleNumber: string; receipt: { supplier: { name: string }; coffeeLot: { code: string }; purchase?: { purchaseNumber: string } | null } }; evaluations: Array<{ evaluatorId: string; evaluatorName: string; score?: number | null; completedAt?: string | null }> };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { credentials: "include", ...init }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message ?? "Não foi possível carregar o laboratório."); return body as T; }

export default function CuppingPage() {
  const [sessions, setSessions] = useState<Session[]>([]);
  const [samples, setSamples] = useState<Array<{ id: string; sampleNumber: string; supplier?: { name: string }; lot?: { code: string } }>>([]);
  const [newSampleId, setNewSampleId] = useState("");
  const [selected, setSelected] = useState<Session | null>(null);
  const [attributes, setAttributes] = useState<Record<string, string>>({});
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [sharedSession, setSharedSession] = useState<{ code: string; publicUrl: string; qrCodeDataUrl: string } | null>(null);
  const load = () => request<Session[]>(`${API}/sessions`).then(setSessions).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível carregar as sessões."));
  useEffect(() => { void load(); void request<typeof samples>(`${getApiBaseUrl()}/receipts/lab-samples`).then(setSamples).catch(() => undefined); }, []);
  const createSession = async () => { if (!newSampleId) return; setSaving(true); setError(""); try { await request(`${API}/sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sampleId: newSampleId }) }); setNewSampleId(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível abrir a sessão."); } finally { setSaving(false); } };
  const createSharedSession = async () => { if (!newSampleId) return; setSaving(true); setError(""); try { const result = await request<{ code: string; publicUrl: string; qrCodeDataUrl: string }>(`${getApiBaseUrl()}/cupping-public/sessions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ kind: "PROFESSIONAL", professionalSampleId: undefined }) }); setSharedSession(result); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível criar a sessão compartilhada."); } finally { setSaving(false); } };
  const score = useMemo(() => { const values = fields.map((field) => Number(attributes[field])).filter(Number.isFinite); return values.length ? (values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(2) : "—"; }, [attributes]);
  const save = async (complete: boolean) => { if (!selected || saving) return; setSaving(true); setError(""); try { await request(`${API}/sessions/${selected.id}/evaluation`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ attributes: Object.fromEntries(fields.map((field) => [field, attributes[field] ? Number(attributes[field]) : undefined])), complete }) }); await load(); if (complete) setSelected(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar a ficha."); } finally { setSaving(false); } };
  return <main className="mx-auto max-w-[1280px] px-1 pb-10"><HumanPageHeader eyebrow="Café Verde" title="Laboratório / Cupping" description="Amostra, pontuação e decisão em uma ficha simples para a bancada." action={<StatusBadge tone="information"><FlaskConical size={13} /> {sessions.length} sessões</StatusBadge>} />
    {error && <p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {sharedSession && <Card className="mb-4 border border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><img src={sharedSession.qrCodeDataUrl} alt={`QR Code da sessão ${sharedSession.code}`} className="h-40 w-40 rounded-xl bg-white p-2" /><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-800">Sua sessão está pronta</p><h2 className="mt-1 text-xl font-bold">{sharedSession.code}</h2><p className="mt-2 break-all text-sm text-emerald-900">{sharedSession.publicUrl}</p><div className="mt-3 flex flex-wrap gap-2"><Button type="button" onClick={() => void navigator.clipboard?.writeText(sharedSession.publicUrl)} className="border bg-white text-stone-700">Copiar link</Button><a href={`https://wa.me/?text=${encodeURIComponent(`Convite para sessão de cupping: ${sharedSession.publicUrl}`)}`} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">Compartilhar por WhatsApp</a></div></div></div></Card>}
    <Card className="mb-4 p-4"><div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs font-semibold text-[var(--bbos-text-secondary)]">Nova sessão a partir da amostra<select value={newSampleId} onChange={(event) => setNewSampleId(event.target.value)} className="mt-1 w-full rounded-xl border border-[var(--bbos-border)] bg-[var(--bbos-surface-subtle)] px-3 py-3 text-sm"><option value="">Selecione uma amostra</option>{samples.map((sample) => <option key={sample.id} value={sample.id}>{sample.sampleNumber} · {sample.supplier?.name ?? "Fornecedor"} · {sample.lot?.code ?? "Lote"}</option>)}</select></label><Button type="button" disabled={!newSampleId || saving} onClick={() => void createSession()}>Abrir sessão</Button><Button type="button" disabled={saving} onClick={() => void createSharedSession()} className="border bg-white text-stone-700"><QrCode size={15} /> Sessão em grupo</Button></div></Card>
    {!sessions.length ? <HumanEmptyState title="Ainda não há sessões de cupping." description="Abra uma sessão a partir de uma amostra recebida para começar." /> : <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{sessions.map((session) => <button key={session.id} type="button" onClick={() => { setSelected(session); setAttributes({}); }} className="text-left"><Card className="h-full p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-xs font-bold text-[var(--bbos-coffee-green)]">{session.code}</p><Badge tone={session.status === "CLOSED" ? "success" : session.status === "REASSESSMENT" ? "warning" : "neutral"}>{session.decision ?? "Em análise"}</Badge></div><h2 className="mt-3 text-base font-bold">{session.sample.receipt.supplier.name}</h2><p className="mt-1 text-xs text-[var(--bbos-text-secondary)]">{session.sample.sampleNumber} · lote {session.sample.receipt.coffeeLot.code}</p><p className="mt-3 text-xs text-[var(--bbos-text-muted)]">{session.evaluations.length} ficha(s) · protocolo {session.protocol}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-[var(--bbos-action-primary)]">Abrir ficha <ArrowRight size={13} /></span></Card></button>)}</section>}
    {selected && <div className="fixed inset-0 z-50 bg-black/30 p-3"><section className="mx-auto flex h-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-[var(--bbos-surface)] shadow-xl"><header className="flex items-start justify-between border-b p-4"><div><p className="text-xs font-bold text-[var(--bbos-coffee-green)]">{selected.code} · {selected.sample.sampleNumber}</p><h2 className="mt-1 text-lg font-bold">{selected.sample.receipt.supplier.name}</h2><p className="text-xs text-[var(--bbos-text-secondary)]">Lote {selected.sample.receipt.coffeeLot.code}</p></div><button type="button" className="text-sm" onClick={() => setSelected(null)}>Fechar</button></header><div className="min-h-0 flex-1 overflow-y-auto p-4"><div className="mb-4 rounded-xl bg-[var(--bbos-info-soft)] p-3 text-sm"><strong>Pontuação calculada: {score}</strong><p className="mt-1 text-xs text-[var(--bbos-text-secondary)]">Cada atributo deve estar entre 0 e 10. Salve parcialmente e retome quando precisar.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{fields.map((field) => <label key={field} className="text-xs font-semibold text-[var(--bbos-text-secondary)]">{labels[field]}<input inputMode="decimal" min="0" max="10" step="0.1" value={attributes[field] ?? ""} onChange={(event) => setAttributes((current) => ({ ...current, [field]: event.target.value }))} className="mt-1 w-full rounded-xl border border-[var(--bbos-border)] bg-[var(--bbos-surface-subtle)] px-3 py-3 text-base text-[var(--bbos-text-primary)] outline-none focus-visible:ring-2 focus-visible:ring-[var(--bbos-focus-ring)]" /></label>)}</div></div><ActionBar className="bg-[var(--bbos-surface)] px-4 pb-4"><Button type="button" disabled={saving} onClick={() => void save(false)} className="bg-[var(--bbos-action-secondary)] text-[var(--bbos-text-primary)]"><Save size={14} /> Salvar parcial</Button><Button type="button" disabled={saving || fields.some((field) => !attributes[field])} onClick={() => void save(true)}><CheckCircle2 size={14} /> {saving ? "Salvando..." : "Salvar e concluir"}</Button></ActionBar></section></div>}
  </main>;
}
