import Image from "next/image";
import Link from "next/link";
import styles from "../page.module.css";
import authority from "../authority.module.css";

export default function SobrePage(){return <main className={styles.page}>
<div className={styles.commerceBar}><span>Frete grátis Sul + Sudeste em compras a partir de R$ 270</span><Link href="/loja#cafes">Escolher cafés →</Link></div>
<header className={styles.header}><Link href="/loja" className={styles.brand}><Image src="/brand/logo/bispo-logo-official-transparent.png" width={176} height={58} alt="Bispo Coffees" priority/></Link><nav className={styles.nav}><Link href="/loja#cafes">Cafés</Link><Link href="/loja#linhas">Linhas</Link><Link href="/loja/descobrir">Descobrir o meu</Link><Link href="/loja/aprender">Aprender</Link><Link href="/loja/sobre">Sobre a empresa</Link></nav><div className={styles.actions}><button aria-label="Buscar">⌕</button><button aria-label="Minha conta">○</button><button aria-label="Sacola">□</button></div></header>
<section className={styles.peopleLayer}><div className={styles.peopleLead}><p>SOBRE A BISPO COFFEES</p><h2>Uma empresa criada a partir de uma vida no café.</h2><span>A Bispo Coffees nasce da experiência acumulada no campo, na prova, na relação com produtores e na construção de mercados para cafés brasileiros.</span></div>
<div className={styles.peopleMarks}><article className={styles.personPrimary}><small>FUNDADOR · QUALIDADE · MERCADO</small><strong>José Rezende</strong><span>Bispo</span></article><div className={styles.thread}><i/><i/><i/><i/></div><article className={styles.personSecondary}><small>FUNDADORA · PRODUÇÃO · SUSTENTABILIDADE</small><strong>Suzi Ninov</strong><span>Fundadora da Bispo Coffees.</span></article></div>
<div className={authority.fieldStory}><figure className={authority.fieldShot}><video src="/cafezal .mp4" muted autoPlay loop playsInline/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>ORIGEM · CAMPO</span><strong>O trabalho começa onde o café nasce.</strong></figcaption></figure><figure className={authority.fieldShot}><img src="/WhatsApp Image 2026-09-01 at 21.36.46 (1).jpeg" alt="José Rezende em propriedade cafeeira"/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>PRESENÇA · RELAÇÃO</span><strong>Qualidade é construída perto de quem produz.</strong></figcaption></figure></div>
<div className={authority.documentaryNote}><p>José Rezende cresceu em uma família de produtores de café no Norte do Paraná e trabalha com qualidade, produtores e mercado desde 2003. A trajetória que começou no campo passou pela prova profissional, certificações, desenvolvimento de origens e abertura de mercados para cafés brasileiros. A Bispo Coffees nasce desse percurso e da parceria com Suzi Ninov, reunindo seleção, produção, sustentabilidade e uma visão simples: escolher melhor antes de o café chegar à xícara.</p><b>Desde 2003</b></div>
<Link className={styles.peopleLink} href="/loja#cafes">Voltar aos cafés →</Link></section>
<section className={styles.valueStrip}><span>Fundadores: José Rezende e Suzi Ninov.</span><span>Origem brasileira.</span><span>Qualidade por critério.</span><span>Do campo à xícara.</span></section>
</main>}
