CREATE TYPE "GreenCoffeePurchaseStatus" AS ENUM ('DRAFT','CONFIRMED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED','CLOSED');
CREATE TYPE "GreenCoffeeSupplierType" AS ENUM ('RURAL_PERSON','COMPANY');
CREATE TYPE "GreenCoffeePackagingType" AS ENUM ('BAG_30_KG','BAG_60_KG','BIG_BAG','OTHER');
CREATE TYPE "GreenCoffeeApprovalStatus" AS ENUM ('PENDING','APPROVED_EXCEPTION','REJECTED','KEPT_BLOCKED');
CREATE TYPE "GreenCoffeeDocumentStatus" AS ENUM ('RECEIVED','PENDING','NOT_APPLICABLE');

ALTER TABLE "Supplier" ADD COLUMN "supplierType" "GreenCoffeeSupplierType" NOT NULL DEFAULT 'COMPANY', ADD COLUMN "legalName" TEXT, ADD COLUMN "stateRegistration" TEXT, ADD COLUMN "ruralRegistration" TEXT, ADD COLUMN "farmName" TEXT, ADD COLUMN "country" TEXT DEFAULT 'Brasil', ADD COLUMN "address" TEXT, ADD COLUMN "contactName" TEXT, ADD COLUMN "contactPhone" TEXT, ADD COLUMN "contactEmail" TEXT;
ALTER TABLE "GreenCoffeeReceipt" ADD COLUMN "purchaseId" TEXT, ADD COLUMN "packagingType" "GreenCoffeePackagingType" NOT NULL DEFAULT 'OTHER', ADD COLUMN "volumeQuantity" INTEGER, ADD COLUMN "nominalWeightKg" DECIMAL(14,3), ADD COLUMN "sampleCollected" BOOLEAN NOT NULL DEFAULT false, ADD COLUMN "visualCondition" TEXT, ADD COLUMN "approvalStatus" "GreenCoffeeApprovalStatus";

CREATE TABLE "GreenCoffeePurchase" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"supplierId" TEXT NOT NULL,"purchaseNumber" TEXT NOT NULL,"status" "GreenCoffeePurchaseStatus" NOT NULL DEFAULT 'DRAFT',"purchasedAt" TIMESTAMP(3) NOT NULL,"buyerId" TEXT NOT NULL,"buyerName" TEXT NOT NULL,"species" TEXT NOT NULL,"originRegion" TEXT NOT NULL,"municipality" TEXT,"state" TEXT,"country" TEXT NOT NULL DEFAULT 'Brasil',"farmName" TEXT,"harvest" TEXT NOT NULL,"variety" TEXT,"process" TEXT,"supplierLotCode" TEXT,"qualityDescription" TEXT,"contractedScreen" TEXT,"maxDefects" INTEGER,"maxMoisturePercent" DECIMAL(5,2),"beverageClassification" TEXT,"minimumScore" DECIMAL(5,2),"technicalSpecifications" TEXT,"packagingType" "GreenCoffeePackagingType" NOT NULL,"volumeQuantity" INTEGER NOT NULL,"nominalUnitWeightKg" DECIMAL(14,3) NOT NULL,"contractedWeightKg" DECIMAL(14,3) NOT NULL,"weightTolerancePercent" DECIMAL(7,3) NOT NULL DEFAULT 0,"pricePerKg" DECIMAL(14,4),"pricePerBag" DECIMAL(14,2),"currency" TEXT NOT NULL DEFAULT 'BRL',"totalValue" DECIMAL(14,2) NOT NULL,"paymentTerms" TEXT,"expectedAt" TIMESTAMP(3),"commercialNotes" TEXT,"idempotencyKey" TEXT NOT NULL,"confirmedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "GreenCoffeePurchase_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GreenCoffeeLabSample" ("id" TEXT NOT NULL,"receiptId" TEXT NOT NULL,"sampleNumber" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "GreenCoffeeLabSample_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GreenCoffeeApprovalRequest" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"purchaseId" TEXT NOT NULL,"receiptId" TEXT NOT NULL,"status" "GreenCoffeeApprovalStatus" NOT NULL DEFAULT 'PENDING',"requiredRole" TEXT NOT NULL,"reason" TEXT NOT NULL,"differences" JSONB NOT NULL,"decidedById" TEXT,"decidedByName" TEXT,"justification" TEXT,"decidedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "GreenCoffeeApprovalRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OperationalNotification" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"purchaseId" TEXT,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"message" TEXT NOT NULL,"targetRole" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "OperationalNotification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GreenCoffeeAuditEvent" ("id" TEXT NOT NULL,"companyId" TEXT NOT NULL,"purchaseId" TEXT,"receiptId" TEXT,"action" TEXT NOT NULL,"actorId" TEXT NOT NULL,"actorName" TEXT NOT NULL,"metadata" JSONB,"occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "GreenCoffeeAuditEvent_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "GreenCoffeePurchase_idempotencyKey_key" ON "GreenCoffeePurchase"("idempotencyKey"); CREATE UNIQUE INDEX "GreenCoffeePurchase_companyId_purchaseNumber_key" ON "GreenCoffeePurchase"("companyId","purchaseNumber"); CREATE INDEX "GreenCoffeePurchase_companyId_status_idx" ON "GreenCoffeePurchase"("companyId","status"); CREATE INDEX "GreenCoffeePurchase_supplierId_idx" ON "GreenCoffeePurchase"("supplierId");
CREATE UNIQUE INDEX "GreenCoffeeLabSample_receiptId_key" ON "GreenCoffeeLabSample"("receiptId"); CREATE UNIQUE INDEX "GreenCoffeeLabSample_sampleNumber_key" ON "GreenCoffeeLabSample"("sampleNumber");
CREATE INDEX "GreenCoffeeApprovalRequest_companyId_status_idx" ON "GreenCoffeeApprovalRequest"("companyId","status"); CREATE INDEX "GreenCoffeeApprovalRequest_receiptId_idx" ON "GreenCoffeeApprovalRequest"("receiptId"); CREATE INDEX "OperationalNotification_companyId_readAt_idx" ON "OperationalNotification"("companyId","readAt"); CREATE INDEX "GreenCoffeeAuditEvent_companyId_occurredAt_idx" ON "GreenCoffeeAuditEvent"("companyId","occurredAt"); CREATE INDEX "GreenCoffeeAuditEvent_purchaseId_idx" ON "GreenCoffeeAuditEvent"("purchaseId"); CREATE INDEX "GreenCoffeeAuditEvent_receiptId_idx" ON "GreenCoffeeAuditEvent"("receiptId"); CREATE INDEX "GreenCoffeeReceipt_purchaseId_idx" ON "GreenCoffeeReceipt"("purchaseId");

ALTER TABLE "GreenCoffeePurchase" ADD CONSTRAINT "GreenCoffeePurchase_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "GreenCoffeePurchase" ADD CONSTRAINT "GreenCoffeePurchase_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GreenCoffeeReceipt" ADD CONSTRAINT "GreenCoffeeReceipt_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "GreenCoffeePurchase"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GreenCoffeeLabSample" ADD CONSTRAINT "GreenCoffeeLabSample_receiptId_fkey" FOREIGN KEY ("receiptId") REFERENCES "GreenCoffeeReceipt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "GreenCoffeeApprovalRequest" ADD CONSTRAINT "GreenCoffeeApprovalRequest_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "GreenCoffeeApprovalRequest" ADD CONSTRAINT "GreenCoffeeApprovalRequest_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "GreenCoffeePurchase"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "GreenCoffeeApprovalRequest" ADD CONSTRAINT "GreenCoffeeApprovalRequest_receiptId_fkey" FOREIGN KEY ("receiptId") REFERENCES "GreenCoffeeReceipt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OperationalNotification" ADD CONSTRAINT "OperationalNotification_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "OperationalNotification" ADD CONSTRAINT "OperationalNotification_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "GreenCoffeePurchase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "GreenCoffeeAuditEvent" ADD CONSTRAINT "GreenCoffeeAuditEvent_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "GreenCoffeeAuditEvent" ADD CONSTRAINT "GreenCoffeeAuditEvent_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "GreenCoffeePurchase"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "GreenCoffeeAuditEvent" ADD CONSTRAINT "GreenCoffeeAuditEvent_receiptId_fkey" FOREIGN KEY ("receiptId") REFERENCES "GreenCoffeeReceipt"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
