"use client";

import * as React from "react";
import Image from "next/image";
import { Check, Coffee, Waves } from "lucide-react";

const weights = ["Leve", "Médio-leve", "Médio", "Médio-alto", "Encorpado"] as const;
const textures = [
  ["Sedoso", "0% 0%"], ["Cremoso", "50% 0%"], ["Aveludado", "100% 0%"],
  ["Licoroso", "0% 100%"], ["Suculento", "50% 100%"], ["Aquoso", "100% 100%"],
] as const;
const haptic = () => { if (typeof navigator !== "undefined" && "vibrate" in navigator) navigator.vibrate(7); };
type Props = { weight?: string; selectedTextures: string[]; score?: number; memory?: string; onWeight(value: string): void; onTextures(value: string[]): void; onScore(value: number): void; onMemory(value: string): void; };

export function CuppingBody({ weight, selectedTextures, score, memory, onWeight, onTextures, onScore, onMemory }: Props) {
  const trackRef = React.useRef<HTMLDivElement>(null);
  const [dragging, setDragging] = React.useState(false);
  const weightIndex = Math.max(0, weights.indexOf(weight as never));
  const chooseAt = React.useCallback((clientX: number) => { const bounds = trackRef.current?.getBoundingClientRect(); if (!bounds) return; const next = weights[Math.round(Math.min(1, Math.max(0, (clientX - bounds.left) / bounds.width)) * 4)]; if (next && next !== weight) { haptic(); onWeight(next); } }, [onWeight, weight]);
  const scores = Array.from({ length: 15 }, (_, index) => 6 + index * .25);
  const toggleTexture = (texture: string) => { haptic(); onTextures(selectedTextures.includes(texture) ? selectedTextures.filter((item) => item !== texture) : [...selectedTextures, texture]); };
  return <div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2 md:items-start lg:gap-5">
    <section className="min-w-0 overflow-hidden rounded-[clamp(1.4rem,4vw,2rem)] border border-[#e6d7c8] bg-[radial-gradient(circle_at_20%_15%,#fffdf9_0,#f7eee4_50%,#ebd9c7_100%)] p-[clamp(1rem,3vw,1.6rem)] shadow-[0_18px_50px_rgba(91,54,35,.1)] md:col-span-2"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#9a725d]">Etapa 05 de 10</p><h2 className="mt-1 text-2xl font-black text-[#432b20]">Corpo</h2><p className="mt-2 text-sm font-semibold text-[#6e5c51]">Como o café ocupa a boca?</p><p className="mt-1 text-xs text-[#87766c]">Perceba o peso, a textura e a sensação tátil.</p></div><Waves className="text-[#b9805e]" /></div>
      <div className="mt-5 rounded-[1.7rem] border border-white/80 bg-[#fffaf5]/75 p-[clamp(.9rem,3vw,1.5rem)]"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#96705b]">Fluxo do Corpo</p><strong className="text-sm text-[#543426]">{weight ?? "Escolha"}</strong></div><div className="relative mt-4 h-[clamp(8rem,22vw,12rem)] overflow-hidden rounded-[1.4rem] bg-[linear-gradient(180deg,#fffdfa,#f4e6d9)]">
        <div className="absolute inset-x-[5%] top-1/2 -translate-y-1/2 transition-all duration-400 motion-reduce:transition-none" style={{ height: `${18 + weightIndex * 13}%`, filter: `drop-shadow(0 ${3 + weightIndex * 2}px ${5 + weightIndex * 2}px rgba(92,52,31,.${12 + weightIndex * 3}))` }}><span className="absolute inset-0 rounded-[48%_55%_45%_52%/48%_43%_57%_52%] bg-[linear-gradient(90deg,rgba(218,177,144,.48),rgba(181,119,78,.7),rgba(231,198,168,.52))] transition-all" style={{ transform: `scaleY(${.72 + weightIndex * .11})`, opacity: .62 + weightIndex * .075 }} /><span className="absolute inset-x-[8%] top-[18%] h-[18%] rounded-full bg-white/35 blur-sm" /></div>
        <div ref={trackRef} className="absolute inset-x-[5%] bottom-2 h-16 touch-none select-none" role="radiogroup" aria-label="Peso do corpo" onPointerDown={(event) => { setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); chooseAt(event.clientX); }} onPointerMove={(event) => dragging && chooseAt(event.clientX)} onPointerUp={(event) => { setDragging(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={() => setDragging(false)}><span className="absolute inset-x-0 top-4 h-1 rounded-full bg-[#dfcbbb]" />{weights.map((item, index) => <button type="button" key={item} role="radio" aria-checked={weight === item} onClick={(event) => { event.stopPropagation(); haptic(); onWeight(item); }} className="absolute top-0 min-h-12 w-[21%] -translate-x-1/2 text-center" style={{ left: `${index * 25}%` }}><span className={`mx-auto mt-1.5 block rounded-full border-[3px] border-[#fffaf5] transition-all ${weight === item ? "size-5 bg-[#8d573b] shadow-[0_4px_12px_rgba(91,49,31,.25)]" : "size-3.5 bg-[#cbb19f]"}`} /><span className="mt-1.5 block text-[clamp(.48rem,1.8vw,.66rem)] font-black leading-3 text-[#705344]">{item}</span></button>)}</div>
      </div><div className="mt-2 flex justify-between text-[10px] font-bold text-[#877268]"><span>Mais leve e fluido</span><span>Mais denso e presente</span></div></div>
    </section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#e6d7c8] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#96705b]">Textura — isso se parece com…</p><p className="mt-1 text-xs text-[#807067]">Selecione uma ou mais referências sensoriais.</p><div className="mt-4 grid grid-cols-2 gap-3 min-[430px]:grid-cols-3 md:grid-cols-2 lg:grid-cols-3">{textures.map(([texture, position]) => { const selected = selectedTextures.includes(texture); return <button type="button" key={texture} aria-pressed={selected} onClick={() => toggleTexture(texture)} className={`relative flex min-h-32 flex-col items-center justify-center rounded-2xl border p-3 text-xs font-black transition active:scale-[.97] ${selected ? "-translate-y-0.5 border-[#9a6245] bg-[#fffaf5] shadow-lg" : "border-[#eadfd5] bg-[#fdfaf7]"}`}><span className="relative size-[clamp(4.5rem,18vw,6rem)] overflow-hidden rounded-full border-2 border-white bg-[#f4e7da] shadow-md"><Image src="/sensory/body/textures/texture-atlas-source.png" alt={texture} fill sizes="96px" className="scale-[3.05] object-cover" style={{ objectPosition: position }} /></span><span className="mt-2 text-[#51372a]">{texture}</span>{selected && <span className="absolute right-2 top-2 grid size-6 place-items-center rounded-full bg-[#8d573b] text-white"><Check size={14} /></span>}</button>; })}</div></section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#e6d7c8] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#96705b]">Sua Xícara — Corpo</p><Coffee size={17} className="text-[#8d573b]" /></div><dl className="mt-3 grid grid-cols-[minmax(4.5rem,auto)_minmax(0,1fr)] gap-x-3 gap-y-2 text-xs"><dt className="font-bold text-[#8c776a]">Peso</dt><dd className="font-black text-[#493126]">{weight ?? "—"}</dd><dt className="font-bold text-[#8c776a]">Textura</dt><dd className="break-words font-black text-[#493126]">{selectedTextures.join(" · ") || "—"}</dd><dt className="font-bold text-[#8c776a]">Qualidade</dt><dd className="font-black text-[#493126]">{score?.toFixed(2).replace(".", ",") ?? "—"}</dd><dt className="font-bold text-[#8c776a]">Memória</dt><dd className="break-words font-black text-[#493126]">{memory?.trim() || "—"}</dd></dl></section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#e6d7c8] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#96705b]">Qualidade do Corpo</p><p className="mt-1 text-xs text-[#807067]">Julgamento técnico independente do peso e da textura.</p><div className="mt-3 grid grid-cols-3 gap-2 min-[430px]:grid-cols-5">{scores.map((value) => <button type="button" key={value} aria-pressed={score === value} onClick={() => onScore(value)} className={`min-h-11 rounded-xl border px-1 text-xs font-black transition active:scale-[.96] ${score === value ? "border-[#875337] bg-[#8d573b] text-white shadow-md" : "border-[#eadfd5] bg-[#fdfaf7] text-[#62483a]"}`}>{value.toFixed(2).replace(".", ",")}</button>)}</div></section>

    <label className="block min-w-0 rounded-[1.7rem] border border-[#e6d7c8] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] text-[10px] font-black uppercase tracking-[.16em] text-[#96705b] shadow-sm">Isso te lembra algo?<textarea maxLength={300} value={memory ?? ""} onChange={(event) => onMemory(event.target.value)} className="mt-2 min-h-20 w-full rounded-2xl border border-[#eadfd5] bg-[#fdfaf7] p-3 text-xs font-normal normal-case tracking-normal text-[#51372a]" placeholder="Memória afetiva — opcional" /></label>
  </div>;
}
