"use client";

import * as React from "react";
import Image from "next/image";
import { Check, ChevronLeft, ChevronRight, Coffee, Droplets, Sparkles, Trash2 } from "lucide-react";

const intensities = ["Baixa", "Suave", "Média", "Viva", "Intensa"] as const;
type AcidityType = { name: string; hint: string; color: string; cover: string; references: ReadonlyArray<readonly [string, string]> };
const acidityTypes: readonly AcidityType[] = [
  { name: "Cítrica", hint: "Brilhante, fresca e definida.", color: "#e3a42e", cover: "/sensory/aroma/frutado/citricos/limao.webp", references: [["Limão", "/sensory/aroma/frutado/citricos/limao.webp"], ["Laranja", "/sensory/flavor/generated/laranja.webp"], ["Tangerina", "/sensory/aroma/frutado/citricos/tangerina.webp"], ["Grapefruit", "/sensory/flavor/generated/grapefruit.webp"]] },
  { name: "Málica", hint: "Fresca, suculenta e arredondada.", color: "#8ca747", cover: "/sensory/flavor/generated/maca-verde.webp", references: [["Maçã verde", "/sensory/flavor/generated/maca-verde.webp"], ["Maçã vermelha", "/sensory/flavor/generated/maca-vermelha.webp"], ["Pera", "/sensory/aroma/frutado/outras-frutas/pera.png"]] },
  { name: "Tartárica", hint: "Estruturada e vínica.", color: "#8e5268", cover: "/sensory/flavor/generated/uva.webp", references: [["Uva", "/sensory/flavor/generated/uva.webp"], ["Tamarindo", "/sensory/flavor/generated/tamara.webp"]] },
  { name: "Láctica", hint: "Suave, macia e cremosa.", color: "#88a8ad", cover: "/sensory/aroma/descriptors/fermentado/iogurte-natural.webp", references: [["Iogurte natural", "/sensory/aroma/descriptors/fermentado/iogurte-natural.webp"], ["Leite fermentado", "/sensory/aroma/descriptors/fermentado/leite-fermentado.webp"], ["Kefir", "/sensory/aroma/descriptors/fermentado/kefir.webp"]] },
  { name: "Fosfórica", hint: "Brilhante, refrescante e vibrante.", color: "#4ca4a3", cover: "", references: [["Brilho refrescante", ""]] },
] as const;
const characters = ["Brilhante", "Delicada", "Suculenta", "Vibrante", "Redonda", "Fresca", "Agressiva", "Áspera", "Outro"];
const haptic = () => { if (typeof navigator !== "undefined" && "vibrate" in navigator) navigator.vibrate(7); };
const toggle = (items: string[], value: string) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value];
const angles = [-90, -18, 54, 126, 198];
const polarPoint = (angle: number, radius = 194) => {
  const radians = (angle - 90) * Math.PI / 180;
  return { x: 210 + radius * Math.cos(radians), y: 210 + radius * Math.sin(radians) };
};
const sectorArc = (centerAngle: number) => {
  const start = polarPoint(centerAngle - 31);
  const end = polarPoint(centerAngle + 31);
  return `M ${start.x} ${start.y} A 194 194 0 0 1 ${end.x} ${end.y}`;
};

type Props = { intensity?: string; selectedTypes: string[]; references: string[]; characters: string[]; score?: number; onIntensity(value: string): void; onTypes(value: string[]): void; onReferences(value: string[]): void; onCharacters(value: string[]): void; onScore(value: number): void; };

function AcidPhoto({ src, name, className = "" }: { src: string; name: string; className?: string }) {
  return src ? <span className={`relative block overflow-hidden bg-[#f7f3e8] ${className}`}><Image src={src} alt={name} fill sizes="80px" className="object-cover" /></span> : <span role="img" aria-label="Representação de brilho e frescor" className={`grid place-items-center overflow-hidden bg-[radial-gradient(circle_at_36%_30%,#fff_0,#ddfff2_20%,#78c9bb_55%,#378c91_100%)] ${className}`}><Sparkles className="text-white drop-shadow" size={23} /></span>;
}

export function CuppingAcidity({ intensity, selectedTypes, references, characters: selectedCharacters, score, onIntensity, onTypes, onReferences, onCharacters, onScore }: Props) {
  const trackRef = React.useRef<HTMLDivElement>(null);
  const [dragging, setDragging] = React.useState(false);
  const [activeType, setActiveType] = React.useState<string | null>(null);
  const [cupOpen, setCupOpen] = React.useState(false);
  const intensityIndex = Math.max(0, intensities.indexOf(intensity as never));
  const chooseAt = React.useCallback((clientX: number) => { const bounds = trackRef.current?.getBoundingClientRect(); if (!bounds) return; const next = intensities[Math.round(Math.min(1, Math.max(0, (clientX - bounds.left) / bounds.width)) * 4)]; if (next && next !== intensity) { haptic(); onIntensity(next); } }, [intensity, onIntensity]);
  const scores = Array.from({ length: 15 }, (_, index) => 6 + index * .25);
  const selectedType = acidityTypes.find((type) => type.name === activeType);
  const countFor = (type: AcidityType) => type.references.filter(([name]) => references.includes(name)).length;
  const removeReference = (name: string) => onReferences(references.filter((item) => item !== name));

  return <div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-2 md:items-start lg:gap-5">
    <section className="min-w-0 overflow-hidden rounded-[clamp(1.4rem,4vw,2rem)] border border-[#dbe4d0] bg-[radial-gradient(circle_at_20%_15%,#fffef8_0,#f5f8e9_50%,#e4ecda_100%)] p-[clamp(1rem,3vw,1.6rem)] shadow-[0_18px_50px_rgba(68,82,43,.1)] md:col-span-2">
      <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#74824e]">Etapa 04 de 10</p><h2 className="mt-1 text-2xl font-black text-[#34402b]">Acidez</h2><p className="mt-2 text-sm font-semibold text-[#68705d]">Como a acidez se apresenta na xícara?</p><p className="mt-1 text-xs text-[#7d8474]">Perceba sua intensidade, caráter e referência sensorial.</p></div><button type="button" onClick={() => setCupOpen((open) => !open)} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#526b37] px-3 text-xs font-black text-white"><Coffee size={16} /> Sua Xícara · {references.length}</button></div>

      <div className="mt-5 rounded-[1.45rem] border border-white/80 bg-white/55 px-[clamp(.75rem,3vw,2rem)] py-4"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#74824e]">Intensidade da acidez</p><strong className="text-sm text-[#40512f]">{intensity ?? "Escolha"}</strong></div><div ref={trackRef} className="relative mt-2 h-16 touch-none select-none" role="radiogroup" aria-label="Intensidade da acidez" onPointerDown={(event) => { setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); chooseAt(event.clientX); }} onPointerMove={(event) => dragging && chooseAt(event.clientX)} onPointerUp={(event) => { setDragging(false); if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); }} onPointerCancel={() => setDragging(false)}><span className="absolute inset-x-[4%] top-4 h-1 rounded-full bg-[#cfd8b4] shadow-inner" /><span className="absolute left-[4%] top-4 h-1 rounded-full bg-gradient-to-r from-[#b7c56e] to-[#698a45] transition-[width]" style={{ width: `${intensityIndex * 23}%` }} />{intensities.map((item, index) => <button type="button" key={item} role="radio" aria-checked={intensity === item} onClick={(event) => { event.stopPropagation(); haptic(); onIntensity(item); }} className="absolute top-0 min-h-12 w-[20%] -translate-x-1/2 text-center" style={{ left: `${4 + index * 23}%` }}><span className={`mx-auto mt-2 block rounded-full border-[3px] border-[#fbfff2] transition-all ${intensity === item ? "size-5 bg-[#718d43] shadow-[0_4px_12px_rgba(76,97,45,.28)]" : "size-3.5 bg-[#b7c39a]"}`} /><span className="mt-1.5 block text-[clamp(.53rem,2vw,.7rem)] font-black text-[#5e694e]">{item}</span></button>)}</div></div>

      {cupOpen && <div className="mt-3 rounded-[1.4rem] border border-[#d9e2cc] bg-[#fffef9] p-4 shadow-lg"><div className="flex items-center justify-between"><p className="text-xs font-black uppercase text-[#52633f]">Sua Xícara — Acidez</p><button type="button" onClick={() => setCupOpen(false)} className="min-h-11 px-3 text-xs font-black text-[#52633f]">Voltar à bússola</button></div>{references.length ? <div className="mt-3 space-y-4">{selectedTypes.map((typeName) => { const type = acidityTypes.find((item) => item.name === typeName); const items = type?.references.filter(([name]) => references.includes(name)) ?? []; return items.length ? <div key={typeName}><p className="text-[9px] font-black uppercase tracking-[.14em]" style={{ color: type?.color }}>{typeName}</p><div className="mt-2 space-y-2">{items.map(([name, asset]) => <div key={name} className="flex min-h-12 items-center gap-2 rounded-xl bg-[#f7f9ef] p-2"><AcidPhoto src={asset} name={name} className="size-9 rounded-full" /><span className="flex-1 text-xs font-black text-[#45513b]">{name}</span><button type="button" onClick={() => removeReference(name)} aria-label={`Remover ${name}`} className="grid size-11 place-items-center rounded-full text-[#8f483b]"><Trash2 size={16} /></button></div>)}</div></div> : null; })}</div> : <p className="mt-3 text-xs text-[#747b6b]">Suas referências aparecerão aqui.</p>}</div>}

      {!activeType ? <div className="relative mx-auto mt-5 aspect-square w-full max-w-[min(92vw,610px)] rounded-full border-[clamp(6px,1vw,10px)] border-white/90 bg-[conic-gradient(from_-126deg,#f3c25e_0_19.5%,#a9c568_20%_39.5%,#a66c7d_40%_59.5%,#a9c5c8_60%_79.5%,#6bb8b5_80%_99.5%,#fff_99.6%)] shadow-[0_24px_55px_rgba(67,81,42,.18)]">
        <svg viewBox="0 0 420 420" aria-hidden="true" className="pointer-events-none absolute -inset-[2px] z-20 size-[calc(100%+4px)] overflow-visible">
          {acidityTypes.map((type, index) => countFor(type) > 0 ? <path key={type.name} d={sectorArc(angles[index] ?? 0)} fill="none" stroke="white" strokeWidth="9" strokeLinecap="round" className="motion-safe:animate-[acidArcIn_280ms_ease-out]" style={{ filter: `drop-shadow(0 3px 4px ${type.color}99)` }} /> : null)}
        </svg>
        <div className="pointer-events-none absolute inset-[21%] rounded-full border border-white/70 bg-[radial-gradient(circle,#fffef7_0,#edf5dc_68%,transparent_70%)] shadow-inner" />
        {acidityTypes.map((type, index) => { const angle = angles[index] ?? 0; const selected = selectedTypes.includes(type.name); const count = countFor(type); const inCup = count > 0; return <button key={type.name} type="button" aria-pressed={inCup} aria-label={`${type.name}, ${count} referências selecionadas`} onClick={() => { haptic(); if (!selected) onTypes([...selectedTypes, type.name]); setActiveType(type.name); }} className={`absolute left-1/2 top-1/2 z-30 flex h-[29%] w-[29%] -translate-x-1/2 -translate-y-1/2 touch-manipulation flex-col items-center justify-center rounded-[45%] text-center text-white outline-none transition-[filter] active:brightness-110 focus-visible:ring-4 focus-visible:ring-white/80 ${inCup ? "drop-shadow-[0_7px_10px_rgba(44,61,31,.22)]" : ""}`} style={{ transform: `translate(-50%,-50%) rotate(${angle}deg) translateY(-116%) rotate(${-angle}deg)` }}><AcidPhoto src={type.cover} name={type.name} className={`size-[clamp(2.8rem,11vw,5rem)] rounded-full border-2 border-white shadow-lg transition ${inCup ? "ring-2 ring-white/70 ring-offset-1 ring-offset-transparent" : ""}`} /><b className="mt-1 text-[clamp(.55rem,1.8vw,.78rem)] leading-3 drop-shadow">{type.name}</b><span className="mt-0.5 max-w-[95px] text-[clamp(.42rem,1.3vw,.58rem)] leading-[9px] opacity-90">{type.hint}</span><span className={`absolute right-[6%] top-[6%] inline-flex min-h-5 min-w-5 items-center justify-center gap-0.5 rounded-full border-2 border-white px-1 text-[9px] font-black shadow transition ${inCup ? "bg-[#4d5f32] text-white" : "bg-white/75 text-[#59644c]"}`}>{inCup && <Check size={9} strokeWidth={3} />}{count}</span></button>; })}
        <div className="absolute left-1/2 top-1/2 z-20 flex aspect-square w-[35%] -translate-x-1/2 -translate-y-1/2 flex-col items-center justify-center rounded-full border-[clamp(5px,.8vw,8px)] border-[#f7f1e7] bg-[radial-gradient(circle_at_44%_35%,#a8c26e_0,#687f42_45%,#4e602f_56%,#fffdf9_58%,#ded5c8_70%,transparent_72%)] text-center text-white shadow-[0_18px_30px_rgba(52,65,35,.25),inset_0_3px_4px_rgba(255,255,255,.7)]"><span className="text-[clamp(.5rem,1.4vw,.7rem)] font-black uppercase tracking-[.12em]">Acidez</span><strong className="mt-0.5 text-[clamp(.75rem,2.2vw,1.1rem)]">{intensity ?? "—"}</strong><span className="mt-0.5 max-w-[80%] text-[clamp(.43rem,1.25vw,.6rem)] leading-3">{selectedTypes.join(" + ") || "Escolha os tipos"}</span><small className="mt-1 text-[clamp(.42rem,1.2vw,.58rem)]">{references.length} referências</small><span className="absolute inset-[14%] rounded-full border border-white/25 transition motion-reduce:transition-none" style={{ transform: `scale(${.8 + intensityIndex * .07})`, boxShadow: `0 0 0 ${2 + intensityIndex * 2}px rgba(225,245,174,.13)` }} /></div>
      </div> : selectedType ? <section className="mt-5 rounded-[1.8rem] border border-white/80 bg-[#fffef9]/90 p-[clamp(1rem,3vw,1.6rem)] shadow-[0_18px_40px_rgba(64,76,40,.12)]"><div className="flex items-center justify-between gap-2"><button type="button" onClick={() => setActiveType(null)} className="inline-flex min-h-11 items-center gap-1 rounded-full px-3 text-xs font-black text-[#52633f]"><ChevronLeft size={17} /> Voltar à bússola</button><button type="button" onClick={() => setCupOpen(true)} className="inline-flex min-h-11 items-center gap-1 rounded-full bg-[#526b37] px-3 text-xs font-black text-white"><Coffee size={15} /> Sua Xícara · {references.length}</button></div><div className="mt-3 flex items-center gap-3"><AcidPhoto src={selectedType.cover} name={selectedType.name} className="size-16 rounded-full border-2 border-white shadow-lg" /><div><p className="text-[10px] font-black uppercase tracking-[.14em]" style={{ color: selectedType.color }}>Tipo de acidez</p><h3 className="text-xl font-black text-[#34402b]">{selectedType.name}</h3><p className="mt-1 text-xs text-[#737b69]">{selectedType.hint}</p></div></div><h4 className="mt-5 text-lg font-black text-[#34402b]">Isso se parece com…</h4><p className="mt-1 text-xs text-[#747b6b]">Selecione uma ou mais referências sensoriais.</p><div className="mt-4 grid grid-cols-2 gap-3 min-[430px]:grid-cols-3">{selectedType.references.map(([name, asset]) => { const selected = references.includes(name); return <button key={name} type="button" aria-pressed={selected} onClick={() => { haptic(); onReferences(toggle(references, name)); }} className={`relative flex min-h-32 flex-col items-center justify-center rounded-2xl border p-3 text-center text-xs font-black transition active:scale-[.97] ${selected ? "-translate-y-0.5 bg-white shadow-lg" : "border-[#e4e8da] bg-[#fafcf5]"}`} style={{ borderColor: selected ? selectedType.color : undefined }}><AcidPhoto src={asset} name={name} className="size-[clamp(4.5rem,18vw,6rem)] rounded-full border-2 border-white shadow-md" /><span className="mt-2 text-[#46513d]">{name}</span>{selected && <span className="absolute right-2 top-2 grid size-6 place-items-center rounded-full bg-[#526b37] text-white"><Check size={14} /></span>}</button>; })}</div><button type="button" onClick={() => setActiveType(null)} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-1 rounded-xl bg-[#526b37] px-4 text-sm font-black text-white shadow-md">Voltar à bússola <ChevronRight size={16} /></button></section> : null}
    </section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#dfe6d5] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#78815f]">Referências selecionadas</p><span className="text-xs font-black text-[#52633f]">{references.length}</span></div>{references.length ? <div className="mt-3 grid grid-cols-2 gap-2 min-[430px]:grid-cols-3 md:grid-cols-2 lg:grid-cols-3">{references.map((name) => { const pair = acidityTypes.flatMap((type) => type.references).find(([reference]) => reference === name); return <div key={name} className="relative flex min-h-20 items-center gap-2 rounded-2xl bg-[#f8faef] p-2"><AcidPhoto src={pair?.[1] ?? ""} name={name} className="size-11 shrink-0 rounded-full" /><b className="min-w-0 flex-1 text-[10px] text-[#45513b]">{name}</b><button type="button" onClick={() => removeReference(name)} aria-label={`Remover ${name}`} className="grid size-11 shrink-0 place-items-center rounded-full text-[#8f483b]"><Trash2 size={15} /></button></div>; })}</div> : <p className="mt-3 text-xs text-[#747b6b]">Explore a bússola para adicionar referências.</p>}<button type="button" onClick={() => setActiveType(null)} className="mt-3 inline-flex min-h-11 items-center gap-1 rounded-full border border-[#dce4d0] px-4 text-xs font-black text-[#52633f]">+ Adicionar referência</button></section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#dfe6d5] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#78815f]">Como ela se comporta?</p><div className="mt-3 grid grid-cols-2 gap-2 min-[430px]:grid-cols-3 md:grid-cols-2 lg:grid-cols-3">{characters.map((character) => { const selected = selectedCharacters.includes(character); return <button type="button" key={character} aria-pressed={selected} onClick={() => { haptic(); onCharacters(toggle(selectedCharacters, character)); }} className={`flex min-h-11 items-center justify-between rounded-full border px-3 text-xs font-black transition active:scale-[.96] ${selected ? "-translate-y-0.5 border-[#688242] bg-[#718b49] text-white shadow-md" : "border-[#e0e6d5] bg-[#fbfcf7] text-[#58614e]"}`}><span>{character}</span>{selected && <Check size={14} />}</button>; })}</div></section>

    <section className="min-w-0 rounded-[1.7rem] border border-[#dfe6d5] bg-white/85 p-[clamp(1rem,2.5vw,1.4rem)] shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#78815f]">Qualidade da acidez</p><p className="mt-1 text-xs text-[#747b6b]">Julgamento técnico independente das referências.</p><div className="mt-3 grid grid-cols-3 gap-2 min-[430px]:grid-cols-5">{scores.map((value) => <button type="button" key={value} aria-pressed={score === value} onClick={() => onScore(value)} className={`min-h-11 rounded-xl border px-1 text-xs font-black transition active:scale-[.96] ${score === value ? "border-[#617c3d] bg-[#6d8748] text-white shadow-md" : "border-[#e0e6d5] bg-[#fbfcf7] text-[#56604d]"}`}>{value.toFixed(2).replace(".", ",")}</button>)}</div></section>

    <section className="min-w-0 rounded-[1.5rem] border border-[#d8e1ca] bg-[#f8faef] px-[clamp(1rem,2vw,1.25rem)] py-4"><div className="flex items-center justify-between"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#78815f]">Acidez</p><span className="inline-flex items-center gap-1 text-[9px] font-black text-[#6c7d55]"><Droplets size={13} /> Pulso {intensity ?? "—"}</span></div><dl className="mt-2 grid grid-cols-[minmax(5.5rem,auto)_minmax(0,1fr)] gap-x-3 gap-y-1.5 text-xs"><dt className="font-bold text-[#7a8370]">Intensidade</dt><dd className="font-black text-[#35402e]">{intensity ?? "—"}</dd><dt className="font-bold text-[#7a8370]">Tipos</dt><dd className="break-words font-black text-[#35402e]">{selectedTypes.join(" · ") || "—"}</dd><dt className="font-bold text-[#7a8370]">Referências</dt><dd className="break-words font-black text-[#35402e]">{references.join(" · ") || "—"}</dd><dt className="font-bold text-[#7a8370]">Caráter</dt><dd className="break-words font-black text-[#35402e]">{selectedCharacters.join(" · ") || "—"}</dd><dt className="font-bold text-[#7a8370]">Qualidade</dt><dd className="font-black text-[#35402e]">{score?.toFixed(2).replace(".", ",") ?? "—"}</dd></dl></section>
    <style jsx global>{`@keyframes acidArcIn { from { opacity: 0; stroke-dasharray: 0 400; } to { opacity: 1; stroke-dasharray: 400 0; } } @media (prefers-reduced-motion: reduce) { .acid-motion { animation: none !important; transition: none !important; } }`}</style>
  </div>;
}
