"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowRight, ClipboardCheck, Factory, PackageCheck, ShieldAlert, Sprout, WalletCards } from "lucide-react";
import { Badge, Card } from "@bbos/ui";
import { getApiRoot, fetchSessionIdentity, type SessionIdentity } from "@/lib/auth-session";
import { getApiBaseUrl } from "@/lib/api-url";

const kg = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 0 });

type HomeData = { salesToday: number; salesMonth: number; openOrders: number; overdueOrders: number; productionActualKg: number; productionPlannedKg: number; pendingLab: number; openPurchases: number; finishedGoodsUnits: number; finishedGoodsReserved: number; greenLots: Array<{ origin: string; code: string; variety: string; currentKg: number; reservedKg: number; status: string }>; alerts: Array<{ tone: "CRÍTICO" | "ATENÇÃO" | "INFORMATIVO" | "POSITIVO"; title: string; impact: string; href: string; action: string }> };
const emptyHome: HomeData = { salesToday: 0, salesMonth: 0, openOrders: 0, overdueOrders: 0, productionActualKg: 0, productionPlannedKg: 0, pendingLab: 0, openPurchases: 0, finishedGoodsUnits: 0, finishedGoodsReserved: 0, greenLots: [], alerts: [] };

export function HomeCommandV1() {
  const [home, setHome] = React.useState<HomeData>(emptyHome);
  const [identity, setIdentity] = React.useState<SessionIdentity | null>(null);
  React.useEffect(() => { const apiRoot = getApiBaseUrl(); const authRoot = getApiRoot(); void Promise.all([fetch(`${apiRoot}/dashboard/home`, { credentials: "include" }).then((r) => r.ok ? r.json() : emptyHome), fetchSessionIdentity(authRoot)]).then(([data, user]) => { setHome(data as HomeData); setIdentity(user); }).catch(() => undefined); }, []);
  const hour = new Date().getHours();
  const greeting = hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite";
  const priorities = home.alerts.map((item) => ({ ...item, icon: item.tone === "CRÍTICO" ? ShieldAlert : item.tone === "ATENÇÃO" ? Factory : item.tone === "POSITIVO" ? WalletCards : ClipboardCheck }));
  const finishedGoods: Array<{ name: string; presentation: string; available: number; dailySales: number; coverage: number; trend: string; tone: "success" | "warning" | "danger"; suggestion: string }> = [];
  const greenLots = home.greenLots.map((lot) => [`${lot.origin} · ${lot.code}`, lot.variety, `${kg.format(lot.currentKg)} kg`, `${kg.format(lot.reservedKg)} kg`, lot.status]);
  const dashboardInventory = { finishedGoodsUnits: home.finishedGoodsUnits, greenCoffeeAvailableKg: home.greenLots.reduce((sum, lot) => sum + lot.currentKg, 0) };
  const executiveV3Data = { inventory: dashboardInventory };
  const executiveV3DemoData = executiveV3Data;
  return <div className="home-command mx-auto w-full max-w-[1600px] space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4">
      <div>
        <p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#087568]">Bispo Coffees · Central de comando</p>
        <h1 className="mt-1 text-3xl font-bold tracking-tight">{greeting}, {identity?.name?.split(" ")[0] ?? ""}!</h1>
        <p className="mt-2 text-sm text-[#626B69]">{priorities.length ? <>Sua operação está estável. Existem <strong className="text-[#111514]">{priorities.length} pontos</strong> que merecem sua atenção hoje.</> : "Nenhuma ocorrência crítica hoje. Operação dentro dos parâmetros."}</p>
        <p className="mt-1 text-[11px] text-[#7A8381]">{identity?.role ?? ""}</p>
      </div>
      <div className="flex items-center gap-2"><Badge tone="neutral">Visão de hoje</Badge><Link href="/dashboard" className="inline-flex items-center gap-1 rounded-xl border border-[#E7E7E3] bg-white px-3 py-2 text-xs font-semibold text-[#626B69]">Dashboard executivo <ArrowRight size={13}/></Link></div>
    </header>

    <section><SectionTitle eyebrow="Prioridade" title="Atenção do gestor" subtitle="Dado → alerta → ação operacional."/><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{priorities.map((item) => <Priority key={item.title} {...item}/>)}</div></section>

    <section><SectionTitle eyebrow="Operação" title="Operação do Dia" subtitle="O que precisa ser acompanhado antes do fechamento."/><div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Operation title="Vendas" icon={WalletCards} href="/vendas" value={new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(home.salesToday)} details={[`Mês: ${new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(home.salesMonth)}`, "Dados do período", "PostgreSQL"]} color="#087568"/><Operation title="Pedidos" icon={PackageCheck} href="/pedidos" value={`${home.openOrders} em aberto`} details={[`${home.overdueOrders} atrasados`, "Dados reais", "PostgreSQL"]} color="#3E73A8"/><Operation title="Produção" icon={Factory} href="/dashboard-industrial" value={`${kg.format(home.productionActualKg)} kg`} details={[`Programado: ${kg.format(home.productionPlannedKg)} kg`, "Dados reais", "PostgreSQL"]} color="#C8923E"/><Operation title="Qualidade" icon={ClipboardCheck} href="/recebimento" value={`${home.pendingLab} lotes em análise`} details={["Aguardando liberação", "Dados reais", "PostgreSQL"]} color="#7867A9"/></div><Card className="mt-3 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#7A8381]">Próximas atividades</p><p className="mt-1 text-sm font-semibold">Acompanhe as etapas pendentes da operação.</p></div><Link href="/producao" className="text-xs font-bold text-[#087568]">Ver operação <ArrowRight className="inline" size={13}/></Link></div></Card></section>

    <section><SectionTitle eyebrow="Estoque" title="Estoque de Produtos Acabados" subtitle="Produtos torrados prontos para venda."/><div className="mt-3 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E7E7E3] p-5"><div><p className="text-2xl font-bold">{kg.format(executiveV3DemoData.inventory.finishedGoodsUnits)} un.</p><p className="text-xs text-[#626B69]">Disponível · cobertura média 19 dias</p></div><Link href="/estoque" className="text-xs font-bold text-[#087568]">Ver detalhes <ArrowRight className="inline" size={13}/></Link></div><div className="grid grid-cols-3 gap-3 border-b border-[#E7E7E3] p-5 text-xs"><Metric label="Físico" value="3.780 un."/><Metric label="Reservado" value="750 un."/><Metric label="SKUs críticos" value="2" tone="warning"/></div><div className="divide-y divide-[#E7E7E3]">{finishedGoods.map((item) => <Link href="/estoque" key={`${item.name}-${item.presentation}`} className="grid gap-2 px-5 py-3 transition hover:bg-[#F7F9F8] md:grid-cols-[1.2fr_.8fr_.8fr_.8fr_.8fr] md:items-center"><div><p className="text-xs font-bold">{item.name} <span className="font-medium text-[#626B69]">{item.presentation}</span></p><p className="text-[10px] text-[#7A8381]">{item.suggestion}</p></div><Metric label="Disponível" value={`${item.available} un.`}/><Metric label="Média 30d" value={`${item.dailySales}/dia`}/><Metric label="Cobertura" value={`${item.coverage} dias`} tone={item.tone}/><span className={`text-right text-sm font-bold ${item.trend === "↑" ? "text-[#16A06A]" : "text-[#D95757]"}`}>{item.trend}</span></Link>)}</div></Card><CoverageChart/></div></section>

    <section><SectionTitle eyebrow="Matéria-prima" title="Café Verde para Produção" subtitle="Matéria-prima disponível para torra."/><div className="mt-3 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-2xl font-bold">{kg.format(executiveV3DemoData.inventory.greenCoffeeAvailableKg)} kg</p><p className="text-xs text-[#626B69]">Disponível para produção</p></div><Sprout className="text-[#087568]" size={22}/></div><div className="mt-5 grid grid-cols-3 gap-3"><Metric label="Reservado" value="8.420 kg"/><Metric label="Cobertura" value="38 dias"/><Metric label="Lotes críticos" value="1" tone="warning"/></div><Link href="/estoque" className="mt-5 inline-flex items-center gap-1 text-xs font-bold text-[#087568]">Ver lotes <ArrowRight size={13}/></Link></Card><Card className="overflow-hidden p-0"><div className="border-b border-[#E7E7E3] p-4"><p className="text-xs font-bold">Lotes para acompanhamento</p></div><div className="divide-y divide-[#E7E7E3]">{greenLots.map(([origin, quality, stock, reserved, status]) => <Link href="/estoque" key={origin} className="grid gap-2 px-4 py-3 transition hover:bg-[#F7F9F8] md:grid-cols-[1.2fr_1fr_.8fr_.8fr_auto] md:items-center"><div><p className="text-xs font-bold">{origin}</p><p className="text-[10px] text-[#7A8381]">{quality}</p></div><span className="text-xs font-semibold">{stock}</span><span className="text-[10px] text-[#626B69]">Reservado {reserved}</span><span className="text-[10px] text-[#626B69]">38 dias</span><Badge tone={status === "ATENÇÃO" ? "warning" : status === "APROVADO" ? "success" : "neutral"}>{status}</Badge></Link>)}</div></Card></div></section>

    <section><SectionTitle eyebrow="Financeiro" title="Visão Financeira" subtitle="Resumo executivo depois da operação e dos estoques."/><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><FinanceMetric label="Disponível em bancos" value="R$ 312.400"/><FinanceMetric label="A receber · 30 dias" value="R$ 384.200"/><FinanceMetric label="A pagar · 30 dias" value="R$ 218.900"/><FinanceMetric label="Vendas no mês" value="R$ 486.320"/><FinanceMetric label="Resultado projetado" value="R$ 97.800"/></div><Link href="/financeiro" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#087568]">Ver financeiro completo <ArrowRight size={13}/></Link></section>
  </div>;
}

function Priority({ tone, title, impact, href, action, icon: Icon }: { tone: "CRÍTICO" | "ATENÇÃO" | "INFORMATIVO" | "POSITIVO"; title: string; impact: string; href: string; action: string; icon: typeof ShieldAlert }) {
  const color = tone === "CRÍTICO" ? "#D95757" : tone === "ATENÇÃO" ? "#E99A35" : tone === "POSITIVO" ? "#16A06A" : "#3E73A8";
  return <Card className="p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between"><span className="grid size-8 place-items-center rounded-full" style={{ color, background: `${color}16` }}><Icon size={15}/></span><span className="text-[9px] font-bold tracking-[.12em]" style={{ color }}>{tone}</span></div><p className="mt-3 text-xs font-bold">{title}</p><p className="mt-1 text-[11px] leading-4 text-[#626B69]">{impact}</p><Link href={href} className="mt-3 inline-flex items-center gap-1 text-[10px] font-bold" style={{ color }}>{action} <ArrowRight size={11}/></Link></Card>;
}
function Operation({ title, value, details, href, color, icon: Icon }: { title: string; value: string; details: string[]; href: string; color: string; icon: typeof Factory }) { return <Link href={href}><Card className="h-full p-4 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className="grid size-8 place-items-center rounded-full" style={{ color, background: `${color}16` }}><Icon size={15}/></span><ArrowRight size={13} className="text-[#7A8381]"/></div><p className="mt-3 text-[10px] font-bold uppercase tracking-wide text-[#626B69]">{title}</p><p className="mt-1 text-lg font-bold">{value}</p><div className="mt-2 space-y-1 text-[10px] text-[#7A8381]">{details.map((detail) => <p key={detail}>{detail}</p>)}</div></Card></Link>; }
function CoverageChart() { return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#087568]">Cobertura</p><h3 className="mt-1 text-sm font-bold">Evolução da cobertura</h3></div><Badge tone="warning">2 em atenção</Badge></div><svg viewBox="0 0 320 150" className="mt-5 h-36 w-full" role="img" aria-label="Evolução da cobertura dos produtos acabados"><line x1="12" x2="308" y1="115" y2="115" stroke="#E7E7E3"/><line x1="12" x2="308" y1="65" y2="65" stroke="#E7E7E3"/><polyline points="12,46 64,58 116,52 168,77 220,86 272,103 308,98" fill="none" stroke="#087568" strokeWidth="3" strokeLinecap="round"/><polyline points="12,30 64,30 116,30 168,30 220,30 272,30 308,30" fill="none" stroke="#C8923E" strokeWidth="1.5" strokeDasharray="5 5"/><text x="12" y="135" fontSize="10" fill="#7A8381">7d</text><text x="145" y="135" fontSize="10" fill="#7A8381">30d</text><text x="284" y="135" fontSize="10" fill="#7A8381">90d</text></svg><p className="mt-2 text-[10px] text-[#7A8381]">Linha caramelo: meta operacional · valores demonstrativos.</p></Card>; }
function Metric({ label, value, tone }: { label: string; value: string; tone?: "success" | "warning" | "danger" }) { return <div><p className="text-[9px] text-[#7A8381]">{label}</p><p className={`mt-1 text-xs font-bold ${tone === "warning" ? "text-[#E99A35]" : tone === "danger" ? "text-[#D95757]" : tone === "success" ? "text-[#16A06A]" : ""}`}>{value}</p></div>; }
function FinanceMetric({ label, value }: { label: string; value: string }) { return <Link href="/financeiro"><Card className="p-4 transition hover:-translate-y-0.5 hover:shadow-md"><p className="text-[10px] font-semibold text-[#626B69]">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></Card></Link>; }
function SectionTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div><p className="text-[9px] font-bold uppercase tracking-[.14em] text-[#087568]">{eyebrow}</p><h2 className="mt-1 text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-[#626B69]">{subtitle}</p></div>; }
