import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, FlaskConical, ShieldAlert } from "lucide-react";
import { Card } from "@bbos/ui";

const sampleLabels = { PENDING: "Aguardando", ASSIGNED: "Preparação", EVALUATED: "Avaliada", CONSOLIDATED: "Consolidada", APPROVED: "Aprovada", BLOCKED: "Bloqueada" } as const;
const sessionLabels = { DRAFT: "Rascunho", OPEN: "Aberta", IN_PROGRESS: "Em andamento", PAUSED: "Pausada", CONSOLIDATING: "Finalizando", CLOSED: "Finalizada", CANCELLED: "Cancelada" } as const;
const decisionLabels = { APPROVED: "Aprovado", APPROVED_WITH_OBSERVATION: "Aprovado com observação", RETEST_REQUIRED: "Reanálise", REJECTED: "Bloqueado" } as const;

export function LabStatusBadge({ status }: { status: string }) {
  const label = sampleLabels[status as keyof typeof sampleLabels] ?? sessionLabels[status as keyof typeof sessionLabels] ?? decisionLabels[status as keyof typeof decisionLabels] ?? status;
  const classes = status === "APPROVED" || status === "APPROVED_WITH_OBSERVATION" || status === "CLOSED" ? "bg-emerald-50 text-emerald-800" : status === "RETEST_REQUIRED" || status === "CONSOLIDATING" || status === "PAUSED" ? "bg-orange-50 text-orange-800" : status === "REJECTED" || status === "BLOCKED" || status === "CANCELLED" ? "bg-red-50 text-red-800" : status === "OPEN" || status === "IN_PROGRESS" || status === "ASSIGNED" || status === "EVALUATED" ? "bg-blue-50 text-blue-800" : "bg-stone-100 text-stone-700";
  return <span className={`inline-flex whitespace-nowrap rounded-full px-2.5 py-1 text-[10px] font-bold ${classes}`}>{label}</span>;
}

export function LabKpiCard({ label, value, href, attention = false }: { label: string; value: number; href: string; attention?: boolean }) {
  return <Link href={href} className="group"><Card className={`h-full p-4 transition group-hover:-translate-y-0.5 group-hover:shadow-sm ${attention ? "border-orange-200 bg-orange-50/30" : ""}`}><div className="flex items-start justify-between"><FlaskConical size={17} className={attention ? "text-orange-700" : "text-forest-700"}/><ArrowRight size={14} className="text-stone-300 group-hover:text-forest-700"/></div><p className="mt-3 text-[10px] font-semibold text-stone-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></Card></Link>;
}

export function LabEmptyState({ title, description, action }: { title: string; description: string; action?: { label: string; href: string } }) {
  return <div className="rounded-xl border border-dashed border-stone-200 bg-stone-50/40 p-7 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={22}/><strong className="mt-2 block text-sm">{title}</strong><p className="mt-1 text-xs text-stone-500">{description}</p>{action && <Link href={action.href} className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-forest-700">{action.label} <ArrowRight size={12}/></Link>}</div>;
}

export type LabQueueItem = { id: string; lotId: string; sampleCode: string; sampleType: string; status: string; createdAt: string; lot: { code: string; origin: string; variety?: string | null; receivedAt: string; supplier: { name: string } } };
export function LabQueueTable({ items, activeSession }: { items: LabQueueItem[]; activeSession?: { id: string } | null }) {
  return <Card className="overflow-hidden"><div className="flex items-center justify-between gap-3 p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-forest-700">Fila operacional</p><h2 className="mt-1 text-lg font-bold">Lotes aguardando prova</h2></div><Link href="/laboratorio/lotes" className="text-xs font-bold text-forest-700">Ver amostras <ArrowRight className="inline" size={13}/></Link></div>{items.length ? <div className="overflow-x-auto"><div className="min-w-[1120px]"><div className="grid grid-cols-[110px_110px_1.2fr_1.2fr_1fr_120px_110px_90px_110px_110px] gap-3 border-y border-stone-100 bg-stone-50 px-5 py-3 text-[9px] font-bold uppercase tracking-wide text-stone-500"><span>Lote</span><span>Amostra</span><span>Produto / Café</span><span>Fornecedor</span><span>Origem</span><span>Entrada</span><span>Finalidade</span><span>Prioridade</span><span>Status</span><span>Ação</span></div>{items.map((sample) => <div key={sample.id} className="grid grid-cols-[110px_110px_1.2fr_1.2fr_1fr_120px_110px_90px_110px_110px] items-center gap-3 border-b border-stone-100 px-5 py-4 text-xs"><strong>{sample.lot.code}</strong><span>{sample.sampleCode}</span><span>{sample.lot.variety ?? "Café verde"}</span><span>{sample.lot.supplier.name}</span><span>{sample.lot.origin}</span><span>{new Date(sample.lot.receivedAt).toLocaleDateString("pt-BR")}</span><span>{sample.sampleType.replaceAll("_", " ")}</span><span className="text-stone-400">—</span><LabStatusBadge status={sample.status}/><Link href={`/laboratorio/sessoes/nova?sampleId=${sample.id}`} className="font-bold text-forest-700">Iniciar prova →</Link></div>)}</div></div> : <div className="p-5"><LabEmptyState title="Tudo em dia." description="Nenhuma amostra está aguardando prova neste momento." action={activeSession ? { label: "Continuar sessão", href: `/laboratorio/sessoes/${activeSession.id}` } : { label: "Ver amostras", href: "/laboratorio/lotes" }}/></div>}</Card>;
}

type LabSession = { id: string; code: string; protocol: string; status: string; createdAt: string; startedAt?: string | null; coordinator: { name: string }; samples: unknown[]; decisions: Array<{ decision: string }> };
export function LabSessionCard({ session }: { session: LabSession }) {
  const approved = session.decisions.filter((item) => item.decision === "APPROVED" || item.decision === "APPROVED_WITH_OBSERVATION").length;
  const retest = session.decisions.filter((item) => item.decision === "RETEST_REQUIRED").length;
  const rejected = session.decisions.filter((item) => item.decision === "REJECTED").length;
  return <Link href={`/laboratorio/sessoes/${session.id}`} className="block rounded-xl border border-stone-200 p-4 transition hover:bg-stone-50"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{session.code}</strong><p className="mt-1 text-xs text-stone-500">{new Date(session.startedAt ?? session.createdAt).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })} · {session.coordinator.name}</p></div><LabStatusBadge status={session.status}/></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-[11px] text-stone-600"><span>{session.samples.length} amostra(s)</span><span>{approved} aprovada(s)</span><span>{retest} reanálise</span><span>{rejected} bloqueada(s)</span></div><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-forest-700">Ver sessão <ArrowRight size={12}/></span></Link>;
}

export function LabQualityDecisionSummary({ data }: { data: { approved: number; retest: number; blocked: number; awaiting: number } }) {
  const items = [["Aprovados para produção", data.approved, "text-emerald-700", CheckCircle2], ["Aguardando reanálise", data.retest, "text-orange-700", Clock3], ["Bloqueados", data.blocked, "text-red-700", ShieldAlert], ["Aguardando decisão", data.awaiting, "text-blue-700", Clock3]] as const;
  return <Card className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-forest-700">Decisões de qualidade</p><h2 className="mt-1 text-lg font-bold">Impacto operacional das provas</h2>{items.some(([,value]) => value > 0) ? <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label,value,color,Icon]) => <div key={label} className="rounded-xl border border-stone-100 bg-stone-50/50 p-4"><Icon size={17} className={color}/><strong className="mt-3 block text-2xl">{value}</strong><p className="mt-1 text-xs text-stone-600">{label}</p></div>)}</div> : <p className="mt-4 rounded-xl border border-dashed p-6 text-center text-xs text-stone-500">Nenhuma decisão de qualidade registrada neste período.</p>}</Card>;
}

type Sensory = { sessionsConsidered: number; scores: { average: number; minimum: number; maximum: number } | null; descriptors: Array<{ name: string; occurrences: number }>; acidityTypes: Array<{ name: string; occurrences: number }> };
export function LabSensoryIntelligence({ sensory }: { sensory: Sensory }) {
  return <Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-forest-700">Inteligência sensorial</p><h2 className="mt-1 text-lg font-bold">Perfil sensorial consolidado</h2></div><Link href="/laboratorio/perfis" className="text-xs font-bold text-forest-700">Ver perfis <ArrowRight className="inline" size={13}/></Link></div>{sensory.sessionsConsidered ? <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr_.8fr_.8fr]"><div><p className="text-[10px] font-bold uppercase text-stone-500">Principais descritores</p><div className="mt-3 flex flex-wrap gap-2">{sensory.descriptors.slice(0,8).map((item) => <span key={item.name} className="rounded-full bg-stone-100 px-3 py-1.5 text-xs font-semibold">{item.name} · {item.occurrences}</span>)}</div></div><div><p className="text-[10px] font-bold uppercase text-stone-500">Acidez predominante</p><strong className="mt-3 block text-lg">{sensory.acidityTypes[0]?.name ?? "—"}</strong></div><div><p className="text-[10px] font-bold uppercase text-stone-500">Pontuação média</p><strong className="mt-3 block text-lg">{sensory.scores?.average.toFixed(1) ?? "—"}</strong><p className="mt-1 text-[11px] text-stone-500">Faixa {sensory.scores ? `${sensory.scores.minimum.toFixed(1)}–${sensory.scores.maximum.toFixed(1)}` : "—"}</p></div><div><p className="text-[10px] font-bold uppercase text-stone-500">Sessões consideradas</p><strong className="mt-3 block text-lg">{sensory.sessionsConsidered}</strong></div></div> : <p className="mt-4 rounded-xl border border-dashed p-6 text-center text-xs text-stone-500">Os perfis sensoriais aparecerão após as primeiras avaliações finalizadas.</p>}</Card>;
}
