"use client";

import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Check, ChevronRight, Clock3, PackageCheck, Plus, Send, Sparkles, X } from "lucide-react";
import { Badge, Card } from "@bbos/ui";

const API = `${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001/api"}/sales-orders`;
const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

type StockOption={productVariantId:string;warehouseId:string;warehouse:string;line:string;lineCode:string;product:string;sku:string;presentationGrams:number;physicalStock:number;reservedStock:number;availableStock:number};
type Customer={id:string;name:string};
type OrderItem={id:string;productName:string;sku:string;quantity:number;unitPrice?:string;totalAmount:string;reservations?:Array<{status:string;quantity:number}>};
type Order={id:string;code:string;orderNumber?:string;status:string;totalAmount:string;subtotal?:string;discount?:string;freight?:string;quantity:number;orderedAt:string;expectedDeliveryDate?:string;customer:Customer;items:OrderItem[];reservations:Array<{id:string;status:string;quantity:number}>};
const statusLabel:Record<string,string>={DRAFT:"Rascunho",CONFIRMED:"Confirmado",RESERVED:"Reservado",PICKING:"Separação",READY_TO_SHIP:"Pronto para expedição",INVOICED:"Faturado",SHIPPED:"Expedido",DELIVERED:"Entregue",CANCELLED:"Cancelado"};
const statusTone:Record<string,"neutral"|"success"|"warning"|"danger">={DRAFT:"neutral",CONFIRMED:"warning",RESERVED:"warning",PICKING:"warning",READY_TO_SHIP:"success",INVOICED:"success",SHIPPED:"success",DELIVERED:"success",CANCELLED:"danger"};
const filters:Array<[string,string]>=[["ALL","Todos"],["DRAFT","Rascunho"],["CONFIRMED","Confirmados"],["RESERVED","Reservados"],["PICKING","Separação"],["READY_TO_SHIP","Prontos"],["INVOICED","Faturados"],["SHIPPED","Expedidos"],["DELIVERED","Concluídos"]];

export default function OrdersPage(){
 const[orders,setOrders]=useState<Order[]>([]);const[customers,setCustomers]=useState<Customer[]>([]);const[variants,setVariants]=useState<StockOption[]>([]);const[creating,setCreating]=useState(false);const[selected,setSelected]=useState<Order|null>(null);const[filter,setFilter]=useState("ALL");const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
 const refresh=async()=>{const[a,b]=await Promise.all([fetch(API),fetch(`${API}/options`)]);if(a.ok)setOrders(await a.json());if(b.ok){const o=await b.json();setCustomers(o.customers);setVariants(o.variants)}};useEffect(()=>{void refresh()},[]);
 const visible=useMemo(()=>filter==="ALL"?orders:orders.filter(i=>i.status===filter),[orders,filter]);const open=orders.filter(i=>!["DELIVERED","CANCELLED","SHIPPED"].includes(i.status));const avgTicket=orders.length?orders.reduce((s,i)=>s+Number(i.totalAmount),0)/orders.length:0;
 const action=async(order:Order,endpoint:string)=>{setBusy(order.id+endpoint);setMessage("");const response=await fetch(`${API}/${order.id}/${endpoint}`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const result=await response.json();setMessage(response.ok?`${order.code} atualizado com sucesso.`:(result.message??"Não foi possível atualizar o pedido."));setBusy("");await refresh()};
 return <div className="mx-auto max-w-[1600px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-violet-700"><Sparkles size={13}/> Comercial inteligente</p><h1 className="mt-1 text-3xl font-bold">Pedidos</h1><p className="mt-2 text-sm text-stone-500">O BBOS acompanha cliente, estoque e condições antes de a venda avançar.</p></div><button onClick={()=>setCreating(true)} className="flex items-center gap-2 rounded-xl bg-forest-900 px-4 py-3 text-xs font-bold text-white"><Plus size={15}/> Novo pedido</button></header>
 {message&&<div className="mt-5 rounded-xl border border-forest-100 bg-forest-50 p-3 text-xs font-semibold text-forest-800">{message}</div>}
 <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><Kpi label="Pedidos em aberto" value={String(open.length)}/><Kpi label="Valor em carteira" value={money.format(open.reduce((s,i)=>s+Number(i.totalAmount),0))}/><Kpi label="Pedidos reservados" value={String(orders.filter(i=>["RESERVED","PICKING","READY_TO_SHIP","INVOICED"].includes(i.status)).length)}/><Kpi label="Aguardando estoque" value={String(orders.filter(i=>i.status==="CONFIRMED").length)}/><Kpi label="Prontos para expedição" value={String(orders.filter(i=>["READY_TO_SHIP","INVOICED"].includes(i.status)).length)}/><Kpi label="Ticket médio" value={money.format(avgTicket)}/></section>
 <div className="mt-7 flex flex-wrap gap-2">{filters.map(([value,label])=><button key={value} onClick={()=>setFilter(value)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${filter===value?"border-forest-200 bg-forest-50":"bg-white"}`}>{label}</button>)}</div>
 <section className="mt-5"><div className="mb-3 flex justify-between"><h2 className="text-lg font-semibold">Pedidos recentes</h2><span className="text-xs text-stone-400">{visible.length} pedidos</span></div><div className="space-y-3">{visible.map(order=><Card key={order.id} className="p-4"><button onClick={()=>setSelected(order)} className="w-full text-left"><div className="flex justify-between"><div><strong>{order.orderNumber??order.code}</strong><p className="text-xs text-stone-500">{order.customer.name}</p></div><div className="flex items-center gap-2"><Status status={order.status}/><strong>{money.format(Number(order.totalAmount))}</strong><ChevronRight size={16}/></div></div></button><div className="mt-3 flex gap-2">{order.status==="DRAFT"&&<button disabled={!!busy} onClick={()=>void action(order,"confirm")} className="rounded-lg bg-forest-900 px-3 py-2 text-xs text-white">Confirmar</button>}{["DRAFT","CONFIRMED","RESERVED","PICKING"].includes(order.status)&&<button disabled={!!busy} onClick={()=>void action(order,"cancel")} className="rounded-lg border px-3 py-2 text-xs">Cancelar</button>}</div></Card>)}{!visible.length&&<Card className="py-14 text-center"><PackageCheck className="mx-auto text-stone-300"/><p className="mt-3 text-sm font-semibold">Nenhum pedido neste filtro</p></Card>}</div></section>
 {creating&&<NewOrder customers={customers} variants={variants} onClose={()=>setCreating(false)} onCreated={async()=>{setCreating(false);await refresh()}}/>}{selected&&<OrderDrawer order={selected} onClose={()=>setSelected(null)}/>}</div>}

function NewOrder({customers,variants,onClose,onCreated}:{customers:Customer[];variants:StockOption[];onClose:()=>void;onCreated:()=>Promise<void>}){const[customerId,setCustomerId]=useState("");const[variantId,setVariantId]=useState("");const[quantity,setQuantity]=useState(1);const[unitPrice,setUnitPrice]=useState(0);const[error,setError]=useState("");const selected=variants.find(v=>v.productVariantId===variantId);const submit=async()=>{if(!selected||!customerId)return setError("Selecione cliente e produto.");const r=await fetch(API,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:`PV-${Date.now().toString().slice(-7)}`,customerId,items:[{productVariantId:selected.productVariantId,warehouseId:selected.warehouseId,quantity,unitPrice}]})});const result=await r.json();if(!r.ok)return setError(result.message??"Não foi possível criar o pedido.");await onCreated()};return <div className="fixed inset-0 z-50 flex justify-end"><button aria-label="Fechar" onClick={onClose} className="absolute inset-0 bg-black/25"/><aside className="relative h-full w-full max-w-lg bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Novo pedido</h2><button onClick={onClose}><X/></button></div><div className="mt-6 space-y-4"><Field label="Cliente"><select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Selecione</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Produto / SKU"><select value={variantId} onChange={e=>setVariantId(e.target.value)}><option value="">Selecione</option>{variants.map(v=><option key={v.productVariantId} value={v.productVariantId}>{v.line} · {v.product} · {v.sku}</option>)}</select></Field><Field label="Quantidade"><input type="number" min="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></Field><Field label="Preço unitário"><input type="number" min="0" step="0.01" value={unitPrice} onChange={e=>setUnitPrice(Number(e.target.value))}/></Field>{error&&<p className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{error}</p>}<button onClick={()=>void submit()} className="w-full rounded-xl bg-forest-900 py-3 text-xs font-bold text-white">Criar pedido</button></div></aside></div>}
function OrderDrawer({order,onClose}:{order:Order;onClose:()=>void}){return <div className="fixed inset-0 z-50 flex justify-end"><button aria-label="Fechar" onClick={onClose} className="absolute inset-0 bg-black/25"/><aside className="relative h-full w-full max-w-xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{order.orderNumber??order.code}</h2><p className="text-xs text-stone-500">{order.customer.name}</p></div><button onClick={onClose}><X/></button></div><div className="mt-6"><Status status={order.status}/><div className="mt-4 flex items-center gap-2 text-xs text-stone-500"><Clock3 size={14}/> Pedido registrado no fluxo operacional.</div></div></aside></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-xs font-semibold">{label}<div className="mt-2 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:px-3 [&>*]:py-3">{children}</div></label>}
function Kpi({label,value}:{label:string;value:string}){return <Card className="p-4"><p className="text-[11px] text-stone-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></Card>}
function Status({status}:{status:string}){return <Badge tone={statusTone[status]??"neutral"}>{statusLabel[status]??status}</Badge>}
