"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowRight, BarChart3, Globe2, ShoppingBag, TriangleAlert } from "lucide-react";
import { Badge, Card } from "@bbos/ui";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3001/api";
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 });
type Product = { id: string; product: string; presentation: string; units: number; revenue: number };
type Dashboard = { vendasOnline: number; pedidosOnline: number; ticketMedio: number; clientes: number; pedidosPendentes: number; vendasUltimos30Dias: number; vendasPeriodoAnterior: number; pedidosUltimos30Dias: number; ticketMedio30Dias: number; historicoVendas: Array<{ label: string; value: number }>; produtosMaisVendidos: Product[]; atencao: Array<{ key: string; label: string; count: number; href: string }>; currency: string; isDemo: boolean };
type Channel = { id: string; code: string; name: string; type: string; currency?: string | null; active: boolean };

export default function CommercePage() {
  const [data, setData] = React.useState<Dashboard | null>(null);
  const [channels, setChannels] = React.useState<Channel[]>([]);
  React.useEffect(() => { Promise.all([fetch(`${API}/commerce/dashboard`).then((r) => r.ok ? r.json() : null), fetch(`${API}/commerce/channels`).then((r) => r.ok ? r.json() : [])]).then(([dashboard, nextChannels]) => { setData(dashboard); setChannels(nextChannels); }); }, []);
  const value = data ?? { vendasOnline: 0, pedidosOnline: 0, ticketMedio: 0, clientes: 0, pedidosPendentes: 0, vendasUltimos30Dias: 0, vendasPeriodoAnterior: 0, pedidosUltimos30Dias: 0, ticketMedio30Dias: 0, historicoVendas: [], produtosMaisVendidos: [], atencao: [], currency: "BRL", isDemo: true };
  const variation = value.vendasPeriodoAnterior ? ((value.vendasUltimos30Dias - value.vendasPeriodoAnterior) / value.vendasPeriodoAnterior) * 100 : null;
  return <div className="mx-auto max-w-[1500px]"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#087568]"><Globe2 size={14}/> BBOS Commerce</p><h1 className="mt-2 text-3xl font-bold">Commerce</h1><p className="mt-2 text-sm text-[#626B69]">Visão gerencial do canal digital conectado ao núcleo BBOS.</p></div><Badge tone={value.isDemo ? "warning" : "success"}>{value.isDemo ? "Sem canal e-commerce" : "Dados reais do canal"}</Badge></header>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Vendas online" value={brl.format(value.vendasOnline)}/><Metric label="Pedidos online" value={String(value.pedidosOnline)}/><Metric label="Ticket médio" value={brl.format(value.ticketMedio)}/><Metric label="Clientes" value={String(value.clientes)}/><Metric label="Pedidos pendentes" value={String(value.pedidosPendentes)}/></div>
    <section className="mt-6 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#087568]">Desempenho da loja</p><h2 className="mt-1 text-lg font-bold">Vendas nos últimos 30 dias</h2></div><Badge tone="neutral">{value.pedidosUltimos30Dias} pedidos</Badge></div><div className="mt-4 flex flex-wrap gap-6"><Metric label="Vendas" value={brl.format(value.vendasUltimos30Dias)}/><Metric label="Ticket médio" value={brl.format(value.ticketMedio30Dias)}/><Metric label="Período anterior" value={variation === null ? "Sem histórico" : `${variation >= 0 ? "+" : ""}${variation.toFixed(1)}%`}/></div>{value.historicoVendas.some((point) => point.value > 0) ? <SalesChart points={value.historicoVendas}/> : <EmptyState text="Ainda não há histórico suficiente de vendas online para exibir evolução."/>}</Card><Attention items={value.atencao}/></section>
    <section className="mt-5 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#087568]">Catálogo</p><h2 className="mt-1 text-lg font-bold">Produtos mais vendidos</h2></div><Link href="/produtos" className="text-xs font-bold text-[#087568]">Catálogo <ArrowRight className="inline" size={13}/></Link></div>{value.produtosMaisVendidos.length ? <div className="mt-4 space-y-3">{value.produtosMaisVendidos.map((item, index) => <Link href={`/vendas/produtos/${item.id}`} key={item.id} className="flex items-center gap-3 rounded-xl border border-[#E7E7E3] p-3 transition hover:bg-[#F7F9F8]"><span className="grid size-7 place-items-center rounded-lg bg-[#F0F0ED] text-xs font-bold text-[#087568]">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{item.product} <span className="font-medium text-[#626B69]">{item.presentation}</span></p><div className="mt-1 h-1 rounded-full bg-[#E7E7E3]"><div className="h-full rounded-full bg-[#087568]" style={{ width: `${Math.min((item.revenue / Math.max(value.vendasUltimos30Dias, 1)) * 100, 100)}%` }}/></div></div><div className="text-right"><p className="text-xs font-bold">{brl.format(item.revenue)}</p><p className="text-[10px] text-[#7A8381]">{item.units} un.</p></div></Link>)}</div> : <EmptyState text="Os produtos aparecerão aqui quando houver pedidos online faturados."/>}</Card><Card className="p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#087568]">Estoque único BBOS</p><h2 className="mt-1 text-lg font-bold">Estoque que merece atenção</h2></div><Link href="/estoque" className="text-xs font-bold text-[#087568]">Ver estoque <ArrowRight className="inline" size={13}/></Link></div><div className="mt-4 rounded-xl border border-dashed border-[#E7E7E3] p-5 text-center"><TriangleAlert className="mx-auto text-[#E99A35]" size={20}/><p className="mt-2 text-xs font-semibold">A análise por canal será ativada com o histórico de pedidos online.</p><p className="mt-1 text-[10px] text-[#7A8381]">O saldo continua sendo o mesmo estoque físico, reservado e disponível do BBOS.</p></div></Card></section>
    <section className="mt-5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#087568]">Canais</p><h2 className="mt-1 text-lg font-bold">Canais de venda</h2></div><Link href="/pedidos" className="text-xs font-bold text-[#087568]">Ver pedidos <ArrowRight className="inline" size={13}/></Link></div><div className="mt-3 grid gap-3 md:grid-cols-3">{channels.length ? channels.map((channel) => <Link href="/pedidos" key={channel.id}><Card className="flex items-center gap-3 p-4 transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-9 place-items-center rounded-full bg-[#F0F0ED] text-[#087568]"><ShoppingBag size={16}/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{channel.name}</p><p className="text-[10px] text-[#7A8381]">{channel.type} · {channel.currency ?? "moeda da conta"}</p></div><ArrowRight size={13} className="text-[#7A8381]"/></Card></Link>) : <Card className="p-4 text-xs text-[#7A8381]">Nenhum canal ativo cadastrado.</Card>}</div></section><p className="mt-5 text-xs text-[#7A8381]">Conversão, carrinhos abandonados, checkout e pagamentos dependem do storefront público e permanecem fora desta versão.</p></div>;
}

function Attention({ items }: { items: Dashboard["atencao"] }) { return <Card className="p-5"><div className="flex items-center gap-2"><TriangleAlert size={16} className="text-[#E99A35]"/><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#E99A35]">Operação comercial</p><h2 className="mt-1 text-lg font-bold">Pedidos que precisam de atenção</h2></div></div>{items.length ? <div className="mt-4 divide-y divide-[#E7E7E3]">{items.map((item) => <Link href={item.href} key={item.key} className="flex items-center justify-between gap-3 py-3 first:pt-0"><span><p className="text-xs font-semibold">{item.label}</p><p className="text-[10px] text-[#7A8381]">Ação operacional necessária</p></span><span className="flex items-center gap-2"><Badge tone="warning">{item.count}</Badge><ArrowRight size={13} className="text-[#7A8381]"/></span></Link>)}</div> : <EmptyState text="Nenhum pedido exige atenção neste momento."/>}</Card>; }
function SalesChart({ points }: { points: Array<{ label: string; value: number }> }) { const max = Math.max(...points.map((point) => point.value), 1); const path = points.map((point, index) => `${index * (280 / Math.max(points.length - 1, 1)) + 20},${112 - (point.value / max) * 85}`).join(" "); return <div className="mt-5"><svg viewBox="0 0 320 140" className="h-36 w-full" role="img" aria-label="Evolução das vendas online"><line x1="20" x2="300" y1="112" y2="112" stroke="#E7E7E3"/><polyline points={path} fill="none" stroke="#087568" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{points.map((point, index) => <text key={point.label} x={index * (280 / Math.max(points.length - 1, 1)) + 20} y="132" textAnchor="middle" fontSize="9" fill="#7A8381">{point.label}</text>)}</svg></div>; }
function EmptyState({ text }: { text: string }) { return <div className="mt-5 rounded-xl border border-dashed border-[#E7E7E3] p-6 text-center text-xs text-[#7A8381]"><BarChart3 className="mx-auto mb-2 text-[#B5C1BD]" size={19}/>{text}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-semibold text-[#626B69]">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>; }
