import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css";
import playful from "./playful.module.css";
import authority from "./authority.module.css";
import DocumentaryHero from "./DocumentaryHero";

const lines=[{name:"GOURMET",need:"Todo dia",copy:"O essencial bem escolhido.",tone:"#F4D54A"},{name:"CLÁSSICOS",need:"Quero conforto",copy:"Conforto com personalidade.",tone:"#E78A38"},{name:"ÉPICOS",need:"Quero descobrir",copy:"Feito para perceber algo novo.",tone:"#387D50"},{name:"RAROS",need:"Quero algo raro",copy:"Poucos. Únicos.",tone:"#B83A31"}];
const products=[{name:"Essencial",line:"GOURMET",notes:"Macio · Doce · Fácil",price:"R$ 52",weight:"500 g",cup:"≈ R$ 2,08 por xícara*",tone:"#F4D54A"},{name:"Intenso",line:"GOURMET",notes:"Presença · Corpo · Conforto",price:"R$ 52",weight:"500 g",cup:"≈ R$ 2,08 por xícara*",tone:"#E2B52E"},{name:"Caramelo",line:"CLÁSSICOS",notes:"Caramelo · Chocolate · Conforto",price:"R$ 68",weight:"500 g",cup:"≈ R$ 2,72 por xícara*",tone:"#E78A38"},{name:"Doce de Leite",line:"CLÁSSICOS",notes:"Mascavo · Doce de leite · Alfajor",price:"R$ 68",weight:"500 g",cup:"≈ R$ 2,72 por xícara*",tone:"#D9A333"},{name:"Tangerina",line:"CLÁSSICOS",notes:"Cítrico · Doce · Fresco",price:"R$ 68",weight:"500 g",cup:"≈ R$ 2,72 por xícara*",tone:"#E88A2E"},{name:"Singular",line:"ÉPICOS",notes:"Frutado · Complexo · Evolutivo",price:"R$ 84",weight:"500 g",cup:"≈ R$ 3,36 por xícara*",tone:"#387D50"},{name:"Sublime",line:"ÉPICOS",notes:"Expressivo · Elegante · Descoberta",price:"R$ 84",weight:"500 g",cup:"≈ R$ 3,36 por xícara*",tone:"#4B8960"},{name:"Raros",line:"RAROS",notes:"Floral · Delicado · Memorável",price:"R$ 54",weight:"250 g",cup:"≈ R$ 4,32 por xícara*",tone:"#B83A31"}];
const moments=[{title:"Começar devagar",cue:"macio · doce · fácil",line:"GOURMET",tone:"#F4D54A",mark:"☀"},{title:"Uma pausa boa",cue:"caramelo · chocolate · conforto",line:"CLÁSSICOS",tone:"#E78A38",mark:"◐"},{title:"Quero perceber algo novo",cue:"fruta · frescor · evolução",line:"ÉPICOS",tone:"#387D50",mark:"✦"},{title:"Hoje merece algo raro",cue:"floral · delicado · memorável",line:"RAROS",tone:"#B83A31",mark:"◇"}];
export default function LojaPage(){return <main className={styles.page}>
<div className={styles.commerceBar}><span>Frete grátis Sul + Sudeste em compras a partir de R$ 270</span><a href="#cafes">Escolher cafés →</a></div>
<header className={styles.header}><a href="#top" className={styles.brand}><Image src="/brand/logo/bispo-logo-official-transparent.png" width={176} height={58} alt="Bispo Coffees" priority/></a><nav className={styles.nav}><a href="#cafes">Cafés</a><a href="#linhas">Linhas</a><Link href="/loja/descobrir">Descobrir o meu</Link><a href="#aprender">Aprender</a></nav><div className={styles.actions}><button aria-label="Buscar">⌕</button><button aria-label="Minha conta">○</button><button aria-label="Sacola">□</button></div></header>
<section id="top" className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>CAFÉS BRASILEIROS <span>origem · prova · consistência</span></p><h1>Antes da xícara,<br/>há uma escolha.</h1><p className={styles.subcopy}>Escolhidos na origem, provados e torrados para entregar consistência na sua xícara.</p><div className={styles.heroButtons}><a className={styles.primaryCta} href="#cafes">Comprar cafés <span>→</span></a><Link className={styles.secondaryCta} href="/loja/descobrir">Descobrir o meu <span>→</span></Link></div><p className={styles.heroProof}>Você não precisa entender de café para escolher bem.</p><div className={styles.colorSignal} aria-hidden="true">{lines.map(line=><i key={line.name} style={{background:line.tone}}/>)}</div></div><DocumentaryHero/></section>
<section className={playful.bridge}><div className={playful.bridgeLead}><small>DO CAMPO À XÍCARA.</small><strong>Do Brasil para o mundo.<br/>Agora, para a sua xícara.</strong></div><div className={playful.bridgeTrail}><span><i>01</i><b>origem</b><small>perto de quem produz</small></span><span><i>02</i><b>prova</b><small>antes de cada escolha</small></span><span><i>03</i><b>consistência</b><small>xícara após xícara</small></span></div></section>
<section id="linhas" className={styles.linesSection}><div className={styles.sectionIntro}><p>ESCOLHA PELO QUE VOCÊ PROCURA</p><h2>Qual Bispo combina com hoje?</h2><span>Primeiro a sensação. Depois, se quiser, você aprofunda.</span></div><div className={styles.lineGrid}>{lines.map(line=><a key={line.name} href="#cafes" className={styles.lineCard} style={{"--tone":line.tone} as React.CSSProperties}><div className={styles.bag}><span>BISPO</span><i/></div><div><small className={styles.needLabel}>{line.need}</small><strong>{line.name}</strong><span>{line.copy}</span></div></a>)}</div></section>
<section id="cafes" className={styles.productsSection}><div className={styles.sectionIntro}><p>OS MAIS ESCOLHIDOS</p><h2>Comece por um perfil.</h2><span>Encontre o sabor que combina com o seu momento.</span></div><div className={styles.productGrid}>{products.map(p=><article key={p.name} className={styles.productCard}><div className={styles.productVisual} style={{"--tone":p.tone} as React.CSSProperties}><div className={styles.productBag}><span>BISPO</span><i/></div></div><div className={styles.productMeta}><p>{p.line}</p><h3>{p.name}</h3><span>{p.notes}</span><div className={styles.buyRow}><div><strong>{p.price} <small>· {p.weight}</small></strong><em className={styles.cupPrice}>{p.cup}</em></div><button>+ Adicionar</button></div></div></article>)}</div><p className={styles.priceNote}>*Referência de 20 g de café por preparo. Frete grátis para Sul e Sudeste a partir de R$ 270.</p></section>
<section className={playful.momentSection}><div className={playful.momentLead}><p>NEM TODO MUNDO ESCOLHE CAFÉ PELO NOME.</p><h2>Às vezes, você escolhe um momento.</h2><span>Passe o olhar. Veja qual sensação encontra você primeiro.</span></div><div className={playful.momentRail}>{moments.map((m,i)=><Link key={m.title} href="/loja/descobrir" className={playful.momentCard} style={{"--moment":m.tone} as React.CSSProperties}><div className={playful.momentTop}><span>{String(i+1).padStart(2,"0")}</span><b>{m.mark}</b></div><div className={playful.orbit}><i/><i/><i/></div><div className={playful.momentCopy}><small>{m.line}</small><strong>{m.title}</strong><span>{m.cue}</span><em>me mostre →</em></div></Link>)}</div></section>
<section className={styles.peopleLayer}><div className={styles.peopleLead}><p>ANTES DA MARCA, EXISTEM TRAJETÓRIAS.</p><h2>Experiência que você não precisa decorar.</h2><span>Ela aparece no campo, na prova, na relação com produtores e na consistência de cada escolha.</span></div><div className={styles.peopleMarks}><article className={styles.personPrimary}><small>SELEÇÃO · QUALIDADE · MERCADO</small><strong>José Rezende</strong><span>Bispo</span></article><div className={styles.thread}><i/><i/><i/><i/></div><article className={styles.personSecondary}><small>CAMPO · PRODUÇÃO · SUSTENTABILIDADE</small><strong>Suzi Ninov</strong><span>Uma presença essencial no processo.</span></article></div><div className={authority.fieldStory}><figure className={authority.fieldShot}><img src="/WhatsApp Image 2026-09-01 at 21.36.46.jpeg" alt="José Rezende conversando com produtora durante trabalho de campo"/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>CAMPO · RELAÇÃO</span><strong>Qualidade começa perto de quem produz.</strong></figcaption></figure><figure className={authority.fieldShot}><img src="/WhatsApp Image 2026-09-01 at 21.36.46 (1).jpeg" alt="José Rezende acompanhando trabalho em propriedade cafeeira"/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>PRESENÇA · CRITÉRIO</span><strong>Antes da escolha, existe presença.</strong></figcaption></figure></div><div className={authority.documentaryNote}><p>Não é uma história criada para a marca. É o trabalho que veio antes dela — campo, produtores, prova e decisão.</p><b>Desde 2003</b></div><a className={styles.peopleLink} href="#aprender">Conhecer a trajetória →</a></section>
<section id="descobrir" className={styles.discovery}><div className={styles.discoveryCopy}><p>NÃO SABE QUAL ESCOLHER?</p><h2>Descubra o seu paladar.</h2><span>Escolha por sabores, memórias e sensações. A lógica do cupping traduzida para uma experiência simples.</span><Link href="/loja/descobrir">Descobrir meu café →</Link></div><div className={styles.discoveryPreview}><div className={styles.miniWheel}><i/><i/><i/><i/><b>BISPO</b></div><div className={styles.miniMandala}><i/><i/><i/><span>acidez</span></div></div></section><section id="aprender" className={styles.valueStrip}><span>Escolhido na origem.</span><span>Provado antes da escolha.</span><span>Torra fresca.</span><span>Frete grátis Sul + Sudeste · R$ 270+</span></section></main>}
