CREATE TABLE IF NOT EXISTS "PackagingMaterial" (
  id TEXT PRIMARY KEY,
  "companyId" TEXT NOT NULL REFERENCES "Company"(id) ON DELETE CASCADE,
  "materialKey" TEXT NOT NULL,
  name TEXT NOT NULL,
  sku TEXT,
  category TEXT NOT NULL DEFAULT 'OTHER',
  unit TEXT NOT NULL DEFAULT 'UN',
  "minimumStock" DECIMAL(14,3) NOT NULL DEFAULT 0,
  "targetStock" DECIMAL(14,3) NOT NULL DEFAULT 0,
  tracked BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE("companyId","materialKey")
);
