'use client';

import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Box, ChevronRight, CircleAlert, Clock3, Factory, TrendingUp } from 'lucide-react';
import { Badge, Card } from '@bbos/ui';
import type { Period } from '@bbos/shared';
import { demoDashboard } from '@/lib/demo-data';

const periods: Array<{ key: Period; label: string }> = [{ key: 'day', label: 'Dia' }, { key: 'week', label: 'Semana' }, { key: 'month', label: 'Mês' }, { key: 'year', label: 'Ano' }];
const chart = [28, 34, 31, 42, 39, 52, 49, 61, 58, 70, 67, 78, 75, 86, 82, 91, 88, 96, 93, 102, 98, 108, 104, 114, 111, 121, 118, 128];

function ResultsCard({ title, projected, actual }: { title: string; projected: number; actual: number }) {
  const format = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', notation: 'compact', maximumFractionDigits: 1 }).format(value);
  const progress = Math.round(actual / projected * 100);
  return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-stone-800">{title}</p><p className="mt-1 text-xs text-stone-500">Projetado x realizado</p></div><TrendingUp size={18} className="text-forest-700" /></div><div className="mt-7 flex items-end justify-between"><div><p className="text-xs text-stone-500">Realizado</p><p className="mt-1 text-2xl font-bold tracking-tight">{format(actual)}</p></div><p className="text-sm font-medium text-stone-500">de {format(projected)}</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-forest-800" style={{ width: `${Math.min(progress, 100)}%` }} /></div><p className="mt-2 text-right text-xs font-semibold text-forest-800">{progress}%</p></Card>;
}

export default function DashboardPage() {
  const [period, setPeriod] = useState<Period>('month');
  const data = demoDashboard;
  return <div className="mx-auto max-w-[1480px]">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-forest-700"><Factory size={14} />Operação Industrial</div><h1 className="font-[var(--font-manrope)] text-3xl font-bold tracking-tight text-stone-950">Dashboard Executivo</h1><p className="mt-2 text-sm text-stone-500">Visão consolidada da Bispo Coffees • atualizado hoje, 10:30</p></div><div className="flex w-fit rounded-xl border bg-white p-1 shadow-sm">{periods.map(item => <button key={item.key} onClick={() => setPeriod(item.key)} className={`rounded-lg px-4 py-2 text-xs font-semibold transition ${period === item.key ? 'bg-forest-900 text-white' : 'text-stone-500 hover:text-stone-900'}`}>{item.label}</button>)}</div></div>

    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric, index) => <Card key={metric.label} className="group p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><p className="text-sm font-medium text-stone-500">{metric.label}</p><span className={`grid size-8 place-items-center rounded-lg ${index < 4 ? 'bg-forest-50 text-forest-700' : 'bg-coffee-100/70 text-coffee-600'}`}>{index < 4 ? <TrendingUp size={16} /> : <Box size={16} />}</span></div><p className="mt-5 text-2xl font-bold tracking-tight text-stone-950">{metric.value}</p><div className="mt-2 flex items-center gap-1.5"><span className={`flex items-center text-xs font-bold ${metric.change >= 0 ? 'text-emerald-700' : 'text-amber-700'}`}>{metric.change >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{Math.abs(metric.change).toLocaleString('pt-BR')}%</span><span className="text-xs text-stone-400">{metric.supportingText}</span></div></Card>)}</section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.65fr_1fr]"><Card className="overflow-hidden p-6"><div className="flex items-start justify-between"><div><h2 className="font-[var(--font-manrope)] text-base font-bold">Evolução do resultado</h2><p className="mt-1 text-xs text-stone-500">Realizado acumulado no período</p></div><Badge tone="success">+12,4% no período</Badge></div><div className="mt-8 flex h-64 items-end gap-1.5 border-b border-l border-stone-100 px-3 pt-4">{chart.map((height, index) => <div key={index} className="group relative flex-1 rounded-t bg-forest-100 transition hover:bg-forest-700" style={{ height: `${height / 1.35}%` }}><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[10px] font-semibold group-hover:block">{height}k</span></div>)}</div><div className="mt-3 flex justify-between pl-3 text-[10px] font-medium uppercase tracking-wider text-stone-400"><span>01 ago</span><span>08 ago</span><span>15 ago</span><span>22 ago</span><span>Hoje</span></div></Card><div className="grid gap-6 sm:grid-cols-2 xl:grid-cols-1"><ResultsCard title="Resultado do mês" {...data.monthlyResult} /><ResultsCard title="Resultado do ano" {...data.yearlyResult} /></div></section>

    <section className="mt-6 grid gap-6 xl:grid-cols-[1.65fr_1fr]"><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-[var(--font-manrope)] text-base font-bold">Alertas operacionais</h2><p className="mt-1 text-xs text-stone-500">Pontos que precisam da sua atenção</p></div><button className="flex items-center gap-1 text-xs font-semibold text-forest-700">Ver todos <ChevronRight size={14} /></button></div><div className="mt-5 divide-y">{data.alerts.map(alert => <div key={alert.id} className="flex items-start gap-4 py-4 first:pt-1"><span className={`mt-0.5 grid size-9 shrink-0 place-items-center rounded-xl ${alert.severity === 'critical' ? 'bg-red-50 text-red-600' : alert.severity === 'warning' ? 'bg-amber-50 text-amber-600' : 'bg-blue-50 text-blue-600'}`}><CircleAlert size={17} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{alert.title}</p><Badge tone={alert.severity === 'critical' ? 'danger' : alert.severity === 'warning' ? 'warning' : 'neutral'}>{alert.area}</Badge></div><p className="mt-1 text-xs text-stone-500">{alert.description}</p></div><ChevronRight size={16} className="mt-2 text-stone-300" /></div>)}</div></Card><Card className="relative overflow-hidden bg-forest-950 p-6 text-white"><div className="absolute -right-16 -top-16 size-52 rounded-full border-[34px] border-white/5" /><div className="relative"><div className="flex items-center gap-2 text-forest-100"><Clock3 size={16} /><p className="text-xs font-semibold uppercase tracking-wider">Ritmo operacional</p></div><p className="mt-7 text-4xl font-bold tracking-tight">94,6%</p><p className="mt-2 text-sm text-white/60">da meta mensal realizada</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[94.6%] rounded-full bg-coffee-400" /></div><div className="mt-5 flex justify-between text-xs"><span className="text-white/50">Meta</span><span className="font-semibold">R$ 514.100</span></div><div className="mt-2 flex justify-between text-xs"><span className="text-white/50">Realizado</span><span className="font-semibold">R$ 486.320</span></div></div></Card></section>
  </div>;
}
