import Image from "next/image";
import Link from "next/link";
import styles from "../page.module.css";
import authority from "../authority.module.css";

export default function AprenderPage(){return <main className={styles.page}>
<div className={styles.commerceBar}><span>Frete grátis Sul + Sudeste em compras a partir de R$ 270</span><Link href="/loja#cafes">Escolher cafés →</Link></div>
<header className={styles.header}><Link href="/loja" className={styles.brand}><Image src="/brand/logo/bispo-logo-official-transparent.png" width={176} height={58} alt="Bispo Coffees" priority/></Link><nav className={styles.nav}><Link href="/loja#cafes">Cafés</Link><Link href="/loja#linhas">Linhas</Link><Link href="/loja/descobrir">Descobrir o meu</Link><Link href="/loja/aprender">Aprender</Link></nav><div className={styles.actions}><button aria-label="Buscar">⌕</button><button aria-label="Minha conta">○</button><button aria-label="Sacola">□</button></div></header>
<section className={styles.peopleLayer}><div className={styles.peopleLead}><p>ANTES DA MARCA, EXISTE UMA TRAJETÓRIA.</p><h2>Experiência que aparece em cada escolha.</h2><span>Campo, prova, produtores e torra fazem parte do processo antes de o café chegar à xícara.</span></div><div className={styles.peopleMarks}><article className={styles.personPrimary}><small>SELEÇÃO · QUALIDADE · MERCADO</small><strong>José Rezende</strong><span>Bispo</span></article><div className={styles.thread}><i/><i/><i/><i/></div><article className={styles.personSecondary}><small>CAMPO · PRODUÇÃO · SUSTENTABILIDADE</small><strong>Suzi Ninov</strong><span>Presença essencial no processo.</span></article></div>
<div className={authority.fieldStory}><figure className={authority.fieldShot}><video src="/cafezal .mp4" muted autoPlay loop playsInline/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>ORIGEM · CAMPO</span><strong>O café começa muito antes da torra.</strong></figcaption></figure><figure className={authority.fieldShot}><img src="/WhatsApp Image 2026-09-01 at 21.36.46 (1).jpeg" alt="José Rezende em propriedade cafeeira, junto ao café no terreiro"/><i className={authority.fieldVeil}/><figcaption className={authority.fieldCaption}><span>PRESENÇA · CRITÉRIO</span><strong>Antes da escolha, existe presença.</strong></figcaption></figure></div>
<div className={authority.documentaryNote}><p>Não é uma história criada para a marca. É um trabalho construído no campo, na prova e na relação com produtores.</p><b>Desde 2003</b></div><Link className={styles.peopleLink} href="/loja#cafes">Voltar aos cafés →</Link></section>
<section className={styles.valueStrip}><span>Escolhido na origem.</span><span>Provado antes da escolha.</span><span>Torra fresca.</span><span>Do campo à xícara.</span></section>
</main>}
