"use client";
import { useEffect,useState } from "react";
import { Card } from "@bbos/ui";
import { getApiBaseUrl } from "@/lib/api-url";

type Wip={id:string;code:string;productionOrderCode:string;productName:string;sku:string;availableKg:number;producedKg:number;status:string;producedAt:string};
type Lot={id:string;code:string;name:string;sku:string;warehouse:string;quantityOnHand:number;initialUnits:number;status:string;manufacturedAt:string;expiresAt?:string|null;productionOrderCode?:string|null};
type Pack={id:string;name:string;sku?:string|null;category:string;unit:string;tracked:boolean;minimumStock:number;onHand:number;reserved:number;available:number};
type Demand={productVariantId:string;name:string;sku:string;netWeightGrams:number;uncoveredDemand:number;available:number;minimumUnits:number;targetUnits:number;safetyUnits:number;recommendedUnits:number};
export default function ProductionControl(){
 const [wip,setWip]=useState<Wip[]>([]),[lots,setLots]=useState<Lot[]>([]),[pack,setPack]=useState<Pack[]>([]),[demand,setDemand]=useState<Demand[]>([]);
 const load=()=>{const r=getApiBaseUrl();void Promise.all([
  fetch(`${r}/operations-flow/wip`,{credentials:"include"}).then(x=>x.ok?x.json():[]),
  fetch(`${r}/operations-flow/finished-lots`,{credentials:"include"}).then(x=>x.ok?x.json():[]),
  fetch(`${r}/operations-flow/packaging`,{credentials:"include"}).then(x=>x.ok?x.json():[]),
  fetch(`${r}/operations-flow/demand`,{credentials:"include"}).then(x=>x.ok?x.json():[])
 ]).then(([a,b,c,d])=>{setWip(a);setLots(b);setPack(c);setDemand(d)}).catch(()=>{});};
 useEffect(load,[]);
 const stockIn=async(m:Pack)=>{const q=Number(window.prompt(`Entrada de ${m.name}: quantidade`));if(!Number.isFinite(q)||q<=0)return;const cost=Number(window.prompt("Custo unitário (opcional)")||0);await fetch(`${getApiBaseUrl()}/operations-flow/packaging/${m.id}/stock-in`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({quantity:q,unitCost:cost,reason:"Entrada manual pelo controle industrial"})});load();};
 return <div className="mx-auto max-w-[1400px] space-y-8">
  <header><p className="text-xs font-bold uppercase tracking-[.14em] text-amber-700">Produção · controle industrial</p><h1 className="mt-2 text-3xl font-bold">Do torrador ao pacote</h1><p className="mt-2 text-sm text-stone-500">Demanda, WIP, insumos e lotes PA em uma única linha operacional.</p></header>

  <section><h2 className="mb-3 text-sm font-bold">Produção recomendada</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{demand.filter(x=>x.recommendedUnits>0).map(x=><Card key={x.productVariantId} className="p-4"><div className="flex justify-between gap-4"><div><p className="font-bold">{x.name} · {x.netWeightGrams} g</p><p className="text-xs text-stone-500">{x.sku}</p></div><strong className="text-lg text-amber-700">{x.recommendedUnits} un.</strong></div><div className="mt-3 grid grid-cols-3 gap-2 text-[10px] text-stone-500"><span>Demanda<br/><b className="text-stone-800">{x.uncoveredDemand}</b></span><span>Disponível<br/><b className="text-stone-800">{x.available}</b></span><span>Alvo<br/><b className="text-stone-800">{Math.max(x.targetUnits,x.minimumUnits)+x.safetyUnits}</b></span></div></Card>)}</div>{!demand.some(x=>x.recommendedUnits>0)&&<p className="text-sm text-stone-500">Nenhuma necessidade adicional de produção calculada.</p>}</section>

  <section><h2 className="mb-3 text-sm font-bold">WIP torrado</h2><div className="grid gap-3 md:grid-cols-2">{wip.map(x=><Card key={x.id} className="p-4"><div className="flex justify-between gap-4"><div><p className="font-bold">{x.code}</p><p className="text-xs text-stone-500">{x.productionOrderCode} · {x.productName} · {x.sku}</p></div><strong>{Number(x.availableKg).toLocaleString("pt-BR",{maximumFractionDigits:2})} kg</strong></div><p className="mt-3 text-[10px] uppercase text-stone-400">Produzido {new Date(x.producedAt).toLocaleDateString("pt-BR")} · {x.status}</p></Card>)}</div>{!wip.length&&<p className="text-sm text-stone-500">Nenhum café torrado aguardando embalagem.</p>}</section>

  <section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-sm font-bold">Embalagens e insumos</h2><p className="text-xs text-stone-500">Controle físico passa a bloquear consumo quando o material estiver marcado como controlado.</p></div></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-[1.4fr_.7fr_.7fr_.7fr_.7fr] bg-stone-50 px-4 py-3 text-[10px] font-bold uppercase text-stone-500"><span>Material</span><span>Saldo</span><span>Mínimo</span><span>Controle</span><span>Ação</span></div>{pack.map(x=><div key={x.id} className="grid grid-cols-[1.4fr_.7fr_.7fr_.7fr_.7fr] items-center border-t px-4 py-3 text-xs"><span><b>{x.name}</b><br/><em className="not-italic text-stone-500">{x.sku||x.category}</em></span><span className={x.tracked&&x.available<=Number(x.minimumStock)?"font-bold text-red-700":"font-semibold"}>{Number(x.available).toLocaleString("pt-BR")} {x.unit}</span><span>{Number(x.minimumStock).toLocaleString("pt-BR")}</span><span>{x.tracked?"Ativo":"Preparação"}</span><button onClick={()=>void stockIn(x)} className="rounded-lg border px-2 py-1.5 font-semibold">Entrada</button></div>)}</div>{!pack.length&&<p className="mt-3 text-sm text-stone-500">Os materiais aparecerão aqui conforme forem usados nas OPs.</p>}</section>

  <section><h2 className="mb-3 text-sm font-bold">Lotes de produto acabado</h2><div className="overflow-hidden rounded-2xl border bg-white"><div className="grid grid-cols-[1.2fr_1fr_.7fr_.7fr_.9fr] bg-stone-50 px-4 py-3 text-[10px] font-bold uppercase text-stone-500"><span>Lote / produto</span><span>OP / armazém</span><span>Inicial</span><span>Saldo</span><span>Validade</span></div>{lots.map(x=><div key={x.id} className="grid grid-cols-[1.2fr_1fr_.7fr_.7fr_.9fr] items-center border-t px-4 py-3 text-xs"><span><b>{x.code}</b><br/><em className="not-italic text-stone-500">{x.name} · {x.sku}</em></span><span>{x.productionOrderCode??"Legado"}<br/><em className="not-italic text-stone-500">{x.warehouse}</em></span><span>{x.initialUnits}</span><span>{x.quantityOnHand}</span><span className={x.expiresAt?"":"font-semibold text-amber-700"}>{x.expiresAt?new Date(x.expiresAt).toLocaleDateString("pt-BR"):"Definir validade"}</span></div>)}</div></section>
 </div>;
}
