ALTER TABLE "SalesOrderItem" ADD COLUMN IF NOT EXISTS "pickedQuantity" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "SalesOrderItem" ADD COLUMN IF NOT EXISTS "pickedAt" TIMESTAMP(3);
ALTER TABLE "SalesOrder" ADD COLUMN IF NOT EXISTS "invoicedAt" TIMESTAMP(3);
