import {
  calculateMachineHourCost,
  calculateRealProductionCost,
} from "@bbos/shared";

export const costCentersDemo = [
  {
    id: "ind-tor",
    code: "IND-TOR",
    name: "Torrefação",
    category: "Industrial",
    actual: 38420,
    budget: 36000,
    method: "Horas de máquina",
    status: "attention",
    resources: 2,
  },
  {
    id: "ind-emp",
    code: "IND-EMP",
    name: "Empacotamento",
    category: "Industrial",
    actual: 27860,
    budget: 26500,
    method: "Unidades produzidas",
    status: "attention",
    resources: 3,
  },
  {
    id: "ind-cq",
    code: "IND-CQ",
    name: "Controle de Qualidade",
    category: "Industrial",
    actual: 12840,
    budget: 13200,
    method: "Kg produzidos",
    status: "normal",
    resources: 4,
  },
  {
    id: "ind-man",
    code: "IND-MAN",
    name: "Manutenção",
    category: "Industrial",
    actual: 9450,
    budget: 8000,
    method: "Horas de máquina",
    status: "critical",
    resources: 0,
  },
  {
    id: "log-arm",
    code: "LOG-ARM",
    name: "Armazém",
    category: "Logística / Estoque",
    actual: 18600,
    budget: 19000,
    method: "Área",
    status: "normal",
    resources: 1,
  },
  {
    id: "log-exp",
    code: "LOG-EXP",
    name: "Expedição",
    category: "Logística / Estoque",
    actual: 14200,
    budget: 14500,
    method: "Unidades produzidas",
    status: "normal",
    resources: 2,
  },
  {
    id: "cor-adm",
    code: "COR-ADM",
    name: "Administrativo",
    category: "Corporativo",
    actual: 32400,
    budget: 31000,
    method: "Receita",
    status: "attention",
    resources: 0,
  },
  {
    id: "cor-com",
    code: "COR-COM",
    name: "Comercial",
    category: "Corporativo",
    actual: 29600,
    budget: 30000,
    method: "Receita",
    status: "normal",
    resources: 0,
  },
] as const;

const machineInput = {
  purchaseValue: 285000,
  residualValue: 28500,
  usefulLifeMonths: 120,
  expectedProductiveHoursPerMonth: 176,
  maintenanceCostEstimatePerMonth: 2200,
  energyConsumptionKwhPerHour: 4.8,
  energyRatePerKwh: 0.94,
  gasConsumptionPerHour: 3.2,
  gasRatePerUnit: 5.7,
  otherHourlyCosts: 1.85,
};
export const resourcesDemo = [
  {
    id: "torrador-01",
    code: "TOR-01",
    name: "Torrador principal",
    type: "Torrador",
    center: "Torrefação",
    utilization: 82,
    hours: 148,
    cost: calculateMachineHourCost(machineInput),
  },
  {
    id: "empacotadora-01",
    code: "EMP-01",
    name: "Empacotadora automática",
    type: "Empacotadora",
    center: "Empacotamento",
    utilization: 74,
    hours: 132,
    cost: calculateMachineHourCost({
      ...machineInput,
      purchaseValue: 164000,
      residualValue: 16400,
      energyConsumptionKwhPerHour: 3.1,
      gasConsumptionPerHour: 0,
      maintenanceCostEstimatePerMonth: 1450,
    }),
  },
] as const;

export const skuCostDemo = calculateRealProductionCost({
  greenCoffee: 12.4,
  roastLoss: 1.84,
  packaging: 2.9,
  labels: 0.42,
  boxes: 0.36,
  directSupplies: 0.28,
  directLabor: 1.7,
  energy: 0.64,
  gas: 0.91,
  machineDepreciation: 0.48,
  maintenance: 0.31,
  otherIndustrial: 0.52,
  allocatedIndustrial: 0.76,
  corporateAllocation: 1.28,
  goodOutputKg: 0.5,
  goodUnits: 1,
  netRevenue: 32.9,
  variableSellingCosts: 1.1,
  sourceIds: [
    "lot-2026-041",
    "op-2026-0112",
    "energy-2026-08",
    "gas-2026-08",
    "cc-tor-2026-08",
  ],
});
