import type { ExecutiveDashboard } from "@bbos/shared";
import {
  executiveDiagnostics,
  salesMapDemo,
} from "./executive-decision-demo-data";

export const demoDashboard: ExecutiveDashboard = {
  updatedAt: "2026-08-06T10:30:00-03:00",
  metricsByPeriod: {
    day: [
      {
        label: "Receita",
        value: "R$ 24.860",
        change: 4.8,
        supportingText: "vs. ontem",
      },
      {
        label: "Lucro operacional",
        value: "R$ 4.920",
        change: 3.2,
        supportingText: "19,8% da receita",
      },
      {
        label: "Margem",
        value: "19,8%",
        change: 0.6,
        supportingText: "meta 20,0%",
      },
      {
        label: "Fluxo de caixa",
        value: "R$ 18.740",
        change: 7.1,
        supportingText: "saldo líquido do dia",
      },
      {
        label: "Produção",
        value: "1.240 kg",
        change: 6.8,
        supportingText: "rendimento 84,9%",
      },
      {
        label: "Café verde",
        value: "42.180 kg",
        change: -0.4,
        supportingText: "52 dias de cobertura",
      },
      {
        label: "Pedidos",
        value: "8",
        change: 14.3,
        supportingText: "7 confirmados",
      },
      {
        label: "Alertas críticos",
        value: "2",
        change: 0,
        supportingText: "requerem ação hoje",
      },
    ],
    week: [
      {
        label: "Receita",
        value: "R$ 118.740",
        change: 8.4,
        supportingText: "vs. semana anterior",
      },
      {
        label: "Lucro operacional",
        value: "R$ 22.560",
        change: 5.9,
        supportingText: "19,0% da receita",
      },
      {
        label: "Margem",
        value: "19,0%",
        change: 0.9,
        supportingText: "meta 20,0%",
      },
      {
        label: "Fluxo de caixa",
        value: "R$ 74.320",
        change: 5.2,
        supportingText: "geração na semana",
      },
      {
        label: "Produção",
        value: "4.680 kg",
        change: 5.6,
        supportingText: "rendimento 84,7%",
      },
      {
        label: "Café verde",
        value: "42.180 kg",
        change: -1.1,
        supportingText: "52 dias de cobertura",
      },
      {
        label: "Pedidos",
        value: "41",
        change: 10.8,
        supportingText: "93% no prazo",
      },
      {
        label: "Alertas críticos",
        value: "2",
        change: -33.3,
        supportingText: "1 resolvido na semana",
      },
    ],
    month: [
      {
        label: "Receita",
        value: "R$ 486.320",
        change: 12.4,
        supportingText: "vs. mês anterior",
      },
      {
        label: "Lucro operacional",
        value: "R$ 91.340",
        change: 8.7,
        supportingText: "18,8% da receita",
      },
      {
        label: "Margem",
        value: "18,8%",
        change: 1.6,
        supportingText: "meta 20,0%",
      },
      {
        label: "Fluxo de caixa",
        value: "R$ 142.680",
        change: 4.2,
        supportingText: "geração no mês",
      },
      {
        label: "Produção",
        value: "18.420 kg",
        change: 6.8,
        supportingText: "rendimento 84,5%",
      },
      {
        label: "Café verde",
        value: "42.180 kg",
        change: -3.2,
        supportingText: "52 dias de cobertura",
      },
      {
        label: "Pedidos",
        value: "164",
        change: 14.1,
        supportingText: "92% no prazo",
      },
      {
        label: "Alertas críticos",
        value: "2",
        change: -33.3,
        supportingText: "4 resolvidos no mês",
      },
    ],
    year: [
      {
        label: "Receita",
        value: "R$ 3.842.600",
        change: 16.2,
        supportingText: "vs. mesmo período de 2025",
      },
      {
        label: "Lucro operacional",
        value: "R$ 718.400",
        change: 13.5,
        supportingText: "18,7% da receita",
      },
      {
        label: "Margem",
        value: "18,7%",
        change: 1.2,
        supportingText: "meta 20,0%",
      },
      {
        label: "Fluxo de caixa",
        value: "R$ 892.300",
        change: 11.3,
        supportingText: "geração no ano",
      },
      {
        label: "Produção",
        value: "142.860 kg",
        change: 9.4,
        supportingText: "rendimento 84,3%",
      },
      {
        label: "Café verde",
        value: "42.180 kg",
        change: -8.1,
        supportingText: "posição atual",
      },
      {
        label: "Pedidos",
        value: "1.284",
        change: 18.6,
        supportingText: "91% no prazo",
      },
      {
        label: "Alertas críticos",
        value: "2",
        change: -50,
        supportingText: "18 resolvidos no ano",
      },
    ],
  },
  roi: {
    current: 18.7,
    target: 20,
    difference: -1.3,
    trend: 1.8,
    status: "attention",
  },
  goals: [
    {
      period: "day",
      target: 26000,
      actual: 24860,
      attainment: 95.6,
      difference: -1140,
      closingProjection: 25520,
      status: "attention",
    },
    {
      period: "week",
      target: 120000,
      actual: 118740,
      attainment: 99,
      difference: -1260,
      closingProjection: 121800,
      status: "attention",
    },
    {
      period: "month",
      target: 514100,
      actual: 486320,
      attainment: 94.6,
      difference: -27780,
      closingProjection: 505600,
      status: "off-track",
    },
    {
      period: "year",
      target: 5200000,
      actual: 3842600,
      attainment: 73.9,
      difference: -1357400,
      closingProjection: 5084000,
      status: "off-track",
    },
  ],
  diagnostics: executiveDiagnostics,
  salesMap: salesMapDemo,
  projections: [
    {
      period: "month",
      expectedToDate: 501200,
      actualToDate: 486320,
      differenceAmount: -14880,
      differencePercent: -3,
      closingProjection: 505600,
      target: 514100,
      status: "attention",
    },
    {
      period: "year",
      expectedToDate: 3975000,
      actualToDate: 3842600,
      differenceAmount: -132400,
      differencePercent: -3.3,
      closingProjection: 5084000,
      target: 5200000,
      status: "attention",
    },
  ],
  alerts: [
    {
      id: "1",
      severity: "critical",
      title: "Estoque de embalagem baixo",
      description: "Três embalagens estão abaixo da cobertura operacional.",
      area: "Estoque",
    },
    {
      id: "2",
      severity: "warning",
      title: "Margem abaixo da meta",
      description: "Margem líquida está 1,2 p.p. abaixo da meta mensal.",
      area: "Financeiro",
    },
    {
      id: "3",
      severity: "warning",
      title: "Produção abaixo da meta",
      description: "Realizado do dia está abaixo do ritmo planejado.",
      area: "Produção",
    },
  ],
};
