import type { PerformanceDiagnostic, SalesMapNode } from "@bbos/shared";

export const executiveDiagnostics: PerformanceDiagnostic[] = [
  {
    id: "diag-roi",
    sourceId: "roi",
    title: "ROI abaixo da meta",
    summary:
      "O retorno está 1,3 p.p. abaixo da meta, concentrado em mix de menor margem e custo logístico.",
    totalImpactAmount: -68400,
    totalImpactPercent: -6.5,
    factors: [
      {
        id: "rf1",
        label: "Mix abaixo da margem-alvo",
        dimension: "product",
        impactAmount: -31800,
        impactPercent: -3,
        entity: "Bispo Essencial 500g",
      },
      {
        id: "rf2",
        label: "Frete acima do previsto",
        dimension: "region",
        impactAmount: -22400,
        impactPercent: -2.1,
        entity: "Região Sul",
      },
      {
        id: "rf3",
        label: "Ociosidade produtiva",
        dimension: "operation",
        impactAmount: -14200,
        impactPercent: -1.4,
        entity: "Linha de envase 02",
      },
    ],
    suggestions: [
      {
        id: "rs1",
        title: "Reequilibrar o mix comercial",
        description:
          "Priorizar SKUs com margem superior a 22% nas próximas campanhas.",
        href: "/produtos",
        linkLabel: "Abrir Produtos",
      },
      {
        id: "rs2",
        title: "Revisar política de frete Sul",
        description:
          "Aplicar pedido mínimo por faixa logística e renegociar rota PR/SC.",
        href: "/pedidos",
        linkLabel: "Abrir Pedidos",
      },
      {
        id: "rs3",
        title: "Ocupar janela da linha 02",
        description:
          "Antecipar OPs do blend Essencial para reduzir custo fixo por kg.",
        href: "/dashboard-industrial",
        linkLabel: "Abrir Industrial",
      },
    ],
  },
  {
    id: "diag-day",
    sourceId: "goal-day",
    title: "Faturamento diário abaixo da meta",
    summary:
      "A diferença de R$ 1.140 está concentrada em pedidos adiados no canal B2B.",
    totalImpactAmount: -1140,
    totalImpactPercent: -4.4,
    factors: [
      {
        id: "df1",
        label: "Pedido reagendado",
        dimension: "customer",
        impactAmount: -760,
        impactPercent: -2.9,
        entity: "Empório Central",
      },
      {
        id: "df2",
        label: "Ruptura temporária",
        dimension: "product",
        impactAmount: -380,
        impactPercent: -1.5,
        entity: "Caramelo Coffee 500g",
      },
    ],
    suggestions: [
      {
        id: "ds1",
        title: "Confirmar expedição prioritária",
        description:
          "Liberar o pedido do Empório Central ainda no segundo turno.",
        href: "/pedidos",
        linkLabel: "Abrir Pedidos",
      },
      {
        id: "ds2",
        title: "Oferecer SKU substituto",
        description:
          "Direcionar clientes para o Essencial 500g até a reposição.",
        href: "/produtos",
        linkLabel: "Abrir Produtos",
      },
    ],
  },
  {
    id: "diag-week",
    sourceId: "goal-week",
    title: "Faturamento semanal em atenção",
    summary:
      "O realizado está 1,0% abaixo da meta; a carteira aberta permite recuperação.",
    totalImpactAmount: -1260,
    totalImpactPercent: -1,
    factors: [
      {
        id: "wf1",
        label: "Conversão menor no canal",
        dimension: "channel",
        impactAmount: -820,
        impactPercent: -0.7,
        entity: "Distribuidores",
      },
      {
        id: "wf2",
        label: "Desempenho regional",
        dimension: "region",
        impactAmount: -440,
        impactPercent: -0.3,
        entity: "Região Sul",
      },
    ],
    suggestions: [
      {
        id: "ws1",
        title: "Ativar carteira distribuidores",
        description: "Contatar as 8 oportunidades com proposta emitida.",
        href: "/pedidos",
        linkLabel: "Abrir Pedidos",
      },
    ],
  },
  {
    id: "diag-month",
    sourceId: "goal-month",
    title: "Meta mensal abaixo do ritmo",
    summary:
      "A lacuna de R$ 27.780 exige recuperação comercial e melhora do mix.",
    totalImpactAmount: -27780,
    totalImpactPercent: -5.4,
    factors: [
      {
        id: "mf1",
        label: "Região abaixo da meta",
        dimension: "region",
        impactAmount: -14200,
        impactPercent: -2.8,
        entity: "Região Sul",
      },
      {
        id: "mf2",
        label: "Cliente com retração",
        dimension: "customer",
        impactAmount: -8380,
        impactPercent: -1.6,
        entity: "Rede Grão Nobre",
      },
      {
        id: "mf3",
        label: "Mix de menor ticket",
        dimension: "product",
        impactAmount: -5200,
        impactPercent: -1,
        entity: "Bispo Essencial 250g",
      },
    ],
    suggestions: [
      {
        id: "ms1",
        title: "Plano de recuperação Sul",
        description:
          "Acionar clientes abaixo da recorrência e revisar cobertura regional.",
        href: "/pedidos",
        linkLabel: "Abrir Pedidos",
      },
      {
        id: "ms2",
        title: "Campanha de mix premium",
        description: "Incentivar Raro e Doce de Leite na carteira ativa.",
        href: "/produtos",
        linkLabel: "Abrir Produtos",
      },
    ],
  },
  {
    id: "diag-year",
    sourceId: "goal-year",
    title: "Meta anual requer aceleração",
    summary:
      "O acumulado representa 73,9% da meta anual; a projeção indica fechamento em 97,8%.",
    totalImpactAmount: -1357400,
    totalImpactPercent: -26.1,
    factors: [
      {
        id: "yf1",
        label: "Receita ainda não realizada",
        dimension: "operation",
        impactAmount: -1120000,
        impactPercent: -21.5,
        entity: "Meses restantes",
      },
      {
        id: "yf2",
        label: "Gap comercial acumulado",
        dimension: "region",
        impactAmount: -237400,
        impactPercent: -4.6,
        entity: "Sul e Centro-Oeste",
      },
    ],
    suggestions: [
      {
        id: "ys1",
        title: "Priorizar pipeline de maior margem",
        description:
          "Concentrar capacidade comercial nas propostas acima de R$ 20 mil.",
        href: "/pedidos",
        linkLabel: "Abrir Pedidos",
      },
    ],
  },
];

const orderNode: SalesMapNode = {
  id: "order-321",
  level: "order",
  name: "PV-2026-0321",
  revenue: 9576,
  volumeKg: 120,
  marginPercent: 24.8,
  growthPercent: 0,
  target: 9200,
  attainment: 104.1,
  salesShare: 2,
  status: "on-track",
};
const productNode: SalesMapNode = {
  id: "product-ess",
  level: "product",
  name: "Bispo Essencial 500g",
  revenue: 28540,
  volumeKg: 358,
  marginPercent: 23.1,
  growthPercent: 8.2,
  target: 30000,
  attainment: 95.1,
  salesShare: 5.9,
  status: "attention",
  children: [orderNode],
};
const customerNode: SalesMapNode = {
  id: "customer-emporio",
  level: "customer",
  name: "Empório Central",
  revenue: 48620,
  volumeKg: 612,
  marginPercent: 22.4,
  growthPercent: 11.5,
  target: 50000,
  attainment: 97.2,
  salesShare: 10,
  status: "attention",
  children: [productNode],
};
const cityNode: SalesMapNode = {
  id: "city-bh",
  level: "city",
  name: "Belo Horizonte",
  revenue: 148200,
  volumeKg: 1920,
  marginPercent: 21.8,
  growthPercent: 13.1,
  target: 145000,
  attainment: 102.2,
  salesShare: 30.5,
  status: "on-track",
  children: [customerNode],
};
const stateMg: SalesMapNode = {
  id: "state-mg",
  level: "state",
  name: "Minas Gerais",
  revenue: 214800,
  volumeKg: 2780,
  marginPercent: 22.1,
  growthPercent: 14.2,
  target: 210000,
  attainment: 102.3,
  salesShare: 44.2,
  status: "on-track",
  children: [cityNode],
};
const stateSp: SalesMapNode = {
  id: "state-sp",
  level: "state",
  name: "São Paulo",
  revenue: 142500,
  volumeKg: 1840,
  marginPercent: 20.4,
  growthPercent: 9.8,
  target: 150000,
  attainment: 95,
  salesShare: 29.3,
  status: "attention",
};
const statePr: SalesMapNode = {
  id: "state-pr",
  level: "state",
  name: "Paraná",
  revenue: 51200,
  volumeKg: 690,
  marginPercent: 17.9,
  growthPercent: -3.4,
  target: 62000,
  attainment: 82.6,
  salesShare: 10.5,
  status: "off-track",
  children: [
    {
      id: "city-curitiba",
      level: "city",
      name: "Curitiba",
      revenue: 36800,
      volumeKg: 492,
      marginPercent: 18.2,
      growthPercent: -2.1,
      target: 45000,
      attainment: 81.8,
      salesShare: 7.6,
      status: "off-track",
    },
  ],
};

const brazilSalesMap: SalesMapNode = {
  id: "country-br",
  level: "country",
  name: "Brasil",
  revenue: 486320,
  volumeKg: 6420,
  marginPercent: 18.8,
  growthPercent: 12.4,
  target: 514100,
  attainment: 94.6,
  salesShare: 100,
  status: "off-track",
  children: [
    {
      id: "region-se",
      level: "region",
      name: "Sudeste",
      revenue: 357300,
      volumeKg: 4620,
      marginPercent: 21.4,
      growthPercent: 12.6,
      target: 360000,
      attainment: 99.3,
      salesShare: 73.5,
      status: "attention",
      children: [stateMg, stateSp],
    },
    {
      id: "region-s",
      level: "region",
      name: "Sul",
      revenue: 74400,
      volumeKg: 1010,
      marginPercent: 17.2,
      growthPercent: -2.8,
      target: 90000,
      attainment: 82.7,
      salesShare: 15.3,
      status: "off-track",
      children: [
        statePr,
        {
          id: "state-sc",
          level: "state",
          name: "Santa Catarina",
          revenue: 23200,
          volumeKg: 320,
          marginPercent: 15.7,
          growthPercent: -1.4,
          target: 28000,
          attainment: 82.9,
          salesShare: 4.8,
          status: "off-track",
        },
      ],
    },
    {
      id: "region-co",
      level: "region",
      name: "Centro-Oeste",
      revenue: 54620,
      volumeKg: 790,
      marginPercent: 19.1,
      growthPercent: 18.5,
      target: 64100,
      attainment: 85.2,
      salesShare: 11.2,
      status: "off-track",
    },
  ],
};

export const salesMapDemo: SalesMapNode = {
  id: "world",
  level: "world",
  name: "Mundo",
  revenue: 486320,
  volumeKg: 6420,
  marginPercent: 18.8,
  growthPercent: 12.4,
  target: 514100,
  attainment: 94.6,
  salesShare: 100,
  status: "off-track",
  children: [brazilSalesMap],
};
