import type { ExecutiveV3Data } from "@bbos/shared";

export const executiveV3DemoData: ExecutiveV3Data = {
  industrial: {
    productionTodayKg: 1240,
    targetTodayKg: 1500,
    efficiencyPercent: 84.5,
    capacityUsedPercent: 68,
    roastLossPercent: 4.2,
    realCostPerKg: 19.45,
    workOrdersInProgress: 8,
    delayedWorkOrders: 2,
  },
  inventory: {
    greenCoffeeAvailableKg: 42180,
    stockValue: 1168400,
    coverageDays: 38,
    coverageTargetDays: 60,
    finishedGoodsUnits: 7320,
    attentionLots: 3,
    criticalItems: 2,
  },
  topCustomers: [
    {
      id: "customer-1",
      name: "Coffee Island",
      primaryValue: 92400,
      revenue: 92400,
      marginPercent: 22.4,
      growthPercent: 11.5,
      salesShare: 19,
    },
    {
      id: "customer-2",
      name: "MAE Coffee",
      primaryValue: 74120,
      revenue: 74120,
      marginPercent: 19.8,
      growthPercent: -2.4,
      salesShare: 15.2,
    },
    {
      id: "customer-3",
      name: "Kios Coffee",
      primaryValue: 58870,
      revenue: 58870,
      marginPercent: 24.1,
      growthPercent: 8.7,
      salesShare: 12.1,
    },
    {
      id: "customer-4",
      name: "Apricity UK",
      primaryValue: 42310,
      revenue: 42310,
      marginPercent: 21.7,
      growthPercent: 6.2,
      salesShare: 8.7,
    },
    {
      id: "customer-5",
      name: "Outros",
      primaryValue: 218620,
      revenue: 218620,
      marginPercent: 18.9,
      growthPercent: 5.3,
      salesShare: 45,
    },
  ],
  topProducts: [
    {
      id: "product-1",
      name: "Bispo Especial 500 g",
      primaryValue: 2180,
      revenue: 173200,
      marginPercent: 24.8,
      growthPercent: 14.2,
    },
    {
      id: "product-2",
      name: "Bispo Clássico 1 kg",
      primaryValue: 1640,
      revenue: 139400,
      marginPercent: 20.3,
      growthPercent: 9.6,
    },
    {
      id: "product-3",
      name: "Bispo Microlote 250 g",
      primaryValue: 980,
      revenue: 92600,
      marginPercent: 28.1,
      growthPercent: 18.4,
    },
    {
      id: "product-4",
      name: "Bispo Essencial 500 g",
      primaryValue: 890,
      revenue: 63200,
      marginPercent: 17.2,
      growthPercent: -3.1,
    },
  ],
  logistics: {
    containersInTransit: 3,
    nextArrivals: 12,
    openPurchases: 215600,
    ordersAwaitingShipment: 14,
    criticalSupplies: 2,
    criticalPackaging: 3,
    isMock: true,
  },
  finance: {
    cash: 142680,
    receivables: 384200,
    payables: 218900,
    marginPercent: 18.8,
    projectedProfit: 97800,
    projectedRoiPercent: 19.4,
    cashTrend: [98, 112, 106, 124, 119, 136, 143],
  },
  attention: [
    {
      id: "att-1",
      problem: "Meta mensal abaixo do ritmo",
      impact: "Gap comercial concentrado no Sul e no mix de menor margem.",
      impactAmount: 27780,
      priority: "high",
      actionLabel: "Ver causas e ações",
      href: "/pedidos",
      diagnosticSourceId: "goal-month",
    },
    {
      id: "att-2",
      problem: "Perda de torra acima da meta",
      impact: "Batch B-108-A adicionou 1,8 kg de perda não planejada.",
      impactAmount: 51,
      priority: "medium",
      actionLabel: "Ver produção",
      href: "/producao",
    },
    {
      id: "att-3",
      problem: "Cobertura de café verde em atenção",
      impact: "Cobertura atual está 8 dias abaixo da meta operacional.",
      impactAmount: 179200,
      priority: "medium",
      actionLabel: "Ver estoque",
      href: "/estoque",
    },
    {
      id: "att-4",
      problem: "OP reservada com atraso",
      impact: "OP-2026-0110 aguarda início desde o dia anterior.",
      impactAmount: 12400,
      priority: "low",
      actionLabel: "Ver produção",
      href: "/producao",
    },
  ],
  aiInsights: [
    {
      id: "ai-1",
      insight: "O mix comercial pode recuperar parte do gap mensal.",
      cause:
        "Participação maior do SKU Essencial, com margem inferior à média.",
      impact: "Oportunidade demonstrativa de até R$ 12,4 mil no resultado.",
      recommendation:
        "Simular priorização dos SKUs Especial e Microlote na carteira ativa.",
      actionLabel: "Analisar produtos",
      href: "/produtos",
      isMock: true,
    },
    {
      id: "ai-2",
      insight: "A capacidade disponível permite antecipar uma OP.",
      cause: "Utilização de 68% e janela disponível na Linha 02.",
      impact:
        "Pode reduzir risco de ruptura sem hora extra, sujeito à validação operacional.",
      recommendation:
        "Revisar sequência das OPs abertas com o gestor industrial.",
      actionLabel: "Abrir produção",
      href: "/producao",
      isMock: true,
    },
    {
      id: "ai-3",
      insight: "Cliente em crescimento merece acompanhamento comercial.",
      cause: "Empório Central cresceu 11,5% e mantém margem acima da média.",
      impact:
        "Oportunidade demonstrativa de ampliar recorrência preservando margem.",
      recommendation:
        "Revisar carteira, frequência e próximos pedidos do cliente.",
      actionLabel: "Ver cliente",
      href: "/pedidos",
      isMock: true,
    },
  ],
};
