import { calculateInventorySummary, type InventoryAlert, type InventoryDashboard, type InventoryLot, type InventoryMovement } from '@bbos/shared';

const timeline = (received: string, stocked: string): InventoryLot['traceability'] => [
  { id: `${received}-r`, label: 'Recebimento', occurredAt: received, status: 'complete' }, { id: `${received}-l`, label: 'Laboratório', occurredAt: received, status: 'complete' }, { id: `${received}-a`, label: 'Aprovação', occurredAt: received, status: 'complete' }, { id: `${received}-e`, label: 'Estoque', occurredAt: stocked, status: 'current' }, { id: `${received}-p`, label: 'Produção', occurredAt: 'Futuro', status: 'future' }, { id: `${received}-b`, label: 'Blend', occurredAt: 'Futuro', status: 'future' }, { id: `${received}-pr`, label: 'Produto', occurredAt: 'Futuro', status: 'future' }, { id: `${received}-pe`, label: 'Pedido', occurredAt: 'Futuro', status: 'future' }, { id: `${received}-c`, label: 'Cliente', occurredAt: 'Futuro', status: 'future' },
];

export const inventoryLotsDemo: InventoryLot[] = [
  { id: 'lot-014', code: 'CV-2026-014', supplier: 'Fazenda Boa Esperança', producer: 'Marcelo Andrade', farm: 'Fazenda Boa Esperança', cityState: 'Carmo de Minas, MG', origin: 'Mantiqueira de Minas', harvest: '2026/27', variety: 'Catuaí Amarelo', process: 'Natural', initialQuantityKg: 4800, availableQuantityKg: 3260, reservedQuantityKg: 400, realCostPerKg: 28.1, totalLotCost: 134880, currentStockValue: 102846, location: 'ACV • Rua A-04', status: 'approved', minimumStockKg: 900, quality: { moisturePercent: 11.2, waterActivity: 0.56, densityGPerL: 718, screen: '16 acima', defects: 5, scaScore: 86.5, notes: 'Perfil limpo e equilibrado.' }, costs: { coffeeValue: 128640, freight: 3600, nonRecoverableTaxes: 0, unloading: 640, initialProcessing: 1600, otherDirectCosts: 400 }, traceability: timeline('06 ago, 08:42', '06 ago, 09:48') },
  { id: 'lot-018', code: 'CV-2026-018', supplier: 'Fazenda Boa Esperança', producer: 'Marcelo Andrade', farm: 'Fazenda Boa Esperança', cityState: 'Varginha, MG', origin: 'Sul de Minas', harvest: '2026/27', variety: 'Bourbon Amarelo', process: 'Natural', initialQuantityKg: 3600, availableQuantityKg: 2940, reservedQuantityKg: 0, realCostPerKg: 31.84, totalLotCost: 93600, currentStockValue: 93609.6, location: 'Bloqueados • B-01', status: 'blocked', minimumStockKg: 800, quality: { moisturePercent: 12.8, waterActivity: 0.67, densityGPerL: 682, screen: '14 acima', defects: 12, scaScore: 82.8, notes: 'Lote segregado conforme regra de qualidade.' }, costs: { coffeeValue: 88920, freight: 2800, nonRecoverableTaxes: 0, unloading: 480, initialProcessing: 1100, otherDirectCosts: 300 }, traceability: timeline('05 ago, 15:28', 'Bloqueado') },
  { id: 'lot-019', code: 'CV-2026-019', supplier: 'Sítio Santa Clara', producer: 'Ana Ribeiro', farm: 'Sítio Santa Clara', cityState: 'Patrocínio, MG', origin: 'Cerrado Mineiro', harvest: '2026/27', variety: 'Mundo Novo', process: 'Cereja descascado', initialQuantityKg: 1800, availableQuantityKg: 1600, reservedQuantityKg: 200, realCostPerKg: 29.6, totalLotCost: 53280, currentStockValue: 53280, location: 'Quarentena • Q-02', status: 'attention', minimumStockKg: 700, quality: { moisturePercent: 12.1, waterActivity: 0.62, densityGPerL: 704, screen: '15 acima', defects: 8, scaScore: 84.2, notes: 'Aguardando decisão técnica documentada.' }, costs: { coffeeValue: 49320, freight: 2250, nonRecoverableTaxes: 0, unloading: 360, initialProcessing: 1050, otherDirectCosts: 300 }, traceability: timeline('06 ago, 10:16', 'Quarentena') },
  { id: 'lot-020', code: 'CV-2026-020', supplier: 'Fazenda Horizonte', producer: 'Luiz Campos', farm: 'Fazenda Horizonte', cityState: 'Varginha, MG', origin: 'Sul de Minas', harvest: '2026/27', variety: 'Acaiá', process: 'Natural', initialQuantityKg: 1200, availableQuantityKg: 1200, reservedQuantityKg: 0, realCostPerKg: 31.92, totalLotCost: 38304, currentStockValue: 38304, location: 'Quarentena • Q-03', status: 'awaiting-lab', minimumStockKg: 600, quality: { notes: 'Análise laboratorial pendente.' }, costs: { coffeeValue: 36000, freight: 1500, nonRecoverableTaxes: 0, unloading: 240, initialProcessing: 360, otherDirectCosts: 204 }, traceability: [{ id: '20-r', label: 'Recebimento', occurredAt: '06 ago, 11:05', status: 'complete' }, { id: '20-l', label: 'Laboratório', occurredAt: 'Aguardando', status: 'current' }, { id: '20-a', label: 'Aprovação', occurredAt: 'Futuro', status: 'future' }, { id: '20-e', label: 'Estoque', occurredAt: 'Futuro', status: 'future' }] },
  { id: 'lot-011', code: 'CV-2026-011', supplier: 'Cooperativa Serra Alta', producer: 'Cooperados Serra Alta', farm: 'Núcleo Serra Alta', cityState: 'Poços de Caldas, MG', origin: 'Mogiana', harvest: '2025/26', variety: 'Catuaí Vermelho', process: 'Natural', initialQuantityKg: 21000, availableQuantityKg: 16700, reservedQuantityKg: 1800, realCostPerKg: 27.42, totalLotCost: 575820, currentStockValue: 507270, location: 'ACV • Rua C-01/08', status: 'approved', minimumStockKg: 4500, quality: { moisturePercent: 11, waterActivity: 0.54, densityGPerL: 712, screen: '16 acima', defects: 7, scaScore: 84.8, notes: 'Lote base para blends recorrentes.' }, costs: { coffeeValue: 548100, freight: 16800, nonRecoverableTaxes: 0, unloading: 2800, initialProcessing: 7020, otherDirectCosts: 1100 }, traceability: timeline('18 jul, 08:10', '18 jul, 11:40') },
  { id: 'lot-012', code: 'CV-2026-012', supplier: 'Fazenda Pedra Branca', producer: 'Carolina Mendes', farm: 'Fazenda Pedra Branca', cityState: 'Cristais Paulista, SP', origin: 'Alta Mogiana', harvest: '2025/26', variety: 'Obatã', process: 'Cereja descascado', initialQuantityKg: 16800, availableQuantityKg: 13080, reservedQuantityKg: 1000, realCostPerKg: 30.15, totalLotCost: 506520, currentStockValue: 424512, location: 'ACV • Rua B-03/07', status: 'approved', minimumStockKg: 3200, quality: { moisturePercent: 10.9, waterActivity: 0.53, densityGPerL: 726, screen: '17 acima', defects: 4, scaScore: 86.1, notes: 'Uniformidade visual e sensorial registrada.' }, costs: { coffeeValue: 480000, freight: 15400, nonRecoverableTaxes: 0, unloading: 2400, initialProcessing: 7520, otherDirectCosts: 1200 }, traceability: timeline('22 jul, 09:20', '22 jul, 13:10') },
];

export const inventoryMovementsDemo: InventoryMovement[] = [
  { id: 'mov-1', type: 'production-reservation', occurredAt: '2026-08-06T10:32:00-03:00', userId: 'user-1', userName: 'Marina Lopes', lotId: 'lot-014', lotCode: 'CV-2026-014', origin: 'ACV • Rua A-04', destination: 'OP-2026-0093', quantityKg: 400, reason: 'Reserva para blend Bispo Essencial' },
  { id: 'mov-2', type: 'internal-transfer', occurredAt: '2026-08-06T09:48:00-03:00', userId: 'user-2', userName: 'Carlos Nunes', lotId: 'lot-019', lotCode: 'CV-2026-019', origin: 'Doca 01', destination: 'Quarentena • Q-02', quantityKg: 1800, reason: 'Segregação após análise laboratorial' },
  { id: 'mov-3', type: 'exit', occurredAt: '2026-08-06T08:05:00-03:00', userId: 'user-1', userName: 'Marina Lopes', lotId: 'lot-011', lotCode: 'CV-2026-011', origin: 'ACV • Rua C-01/08', destination: 'Produção', quantityKg: 1200, reason: 'Consumo OP-2026-0091' },
];

export const inventoryAlertsDemo: InventoryAlert[] = [
  { id: 'ia-1', lotId: 'lot-018', datum: '2.940 kg com status bloqueado', alert: 'Lote bloqueado por qualidade', diagnosis: 'A atividade de água registrada está 0,02 acima da regra configurada.', impactKg: 2940, impactAmount: 93609.6, action: 'Manter segregação e registrar decisão do responsável técnico.', expectedResult: 'Saldo indisponível protegido contra reserva ou saída.', status: 'off-track' },
  { id: 'ia-2', lotId: 'lot-019', datum: 'Umidade 12,1% • limite configurado 12,0%', alert: 'Lote em atenção por umidade', diagnosis: 'Diferença de 0,1 p.p. mantém o lote em quarentena operacional.', impactKg: 1800, impactAmount: 53280, action: 'Abrir o lote e registrar a decisão técnica de qualidade.', expectedResult: 'Liberação ou bloqueio documentado sem risco de uso indevido.', status: 'attention' },
  { id: 'ia-3', lotId: 'lot-020', datum: '1.200 kg sem laudo concluído', alert: 'Estoque aguardando laboratório', diagnosis: 'O recebimento foi concluído, mas a qualidade ainda não liberou o saldo.', impactKg: 1200, impactAmount: 38304, action: 'Priorizar análise laboratorial do lote.', expectedResult: 'Redução do estoque em quarentena e atualização do saldo utilizável.', status: 'attention' },
  { id: 'ia-4', datum: 'Cobertura estimada: 52 dias • meta: 60 dias', alert: 'Cobertura abaixo da meta', diagnosis: 'O consumo médio projetado supera o ritmo atual de reposição.', impactKg: 6480, impactAmount: 191808, action: 'Revisar recebimentos previstos e plano de produção das próximas quatro semanas.', expectedResult: 'Cobertura recomposta sem excesso de estoque.', status: 'attention' },
];

export const inventoryDemoDashboard: InventoryDashboard = { updatedAt: '2026-08-06T12:05:00-03:00', summary: calculateInventorySummary(inventoryLotsDemo, 811), lots: inventoryLotsDemo, movements: inventoryMovementsDemo, alerts: inventoryAlertsDemo };
