import type { SalesPerformanceDashboard } from "@bbos/shared";

const customers = [
  {
    id: "cli-1",
    name: "Empório Central",
    revenue: 48620,
    sharePercent: 28.1,
    growthPercent: 11.5,
  },
  {
    id: "cli-2",
    name: "Rede Grão Nobre",
    revenue: 42800,
    sharePercent: 24.7,
    growthPercent: -2.4,
  },
  {
    id: "cli-3",
    name: "Café do Mercado",
    revenue: 36200,
    sharePercent: 20.9,
    growthPercent: 8.7,
  },
];

export const salesDemoData: SalesPerformanceDashboard = {
  updatedAt: "2026-08-07T10:30:00-03:00",
  period: "month",
  target: 514100,
  actual: 486320,
  attainmentPercent: 94.6,
  closingProjection: 505600,
  marginPercent: 18.8,
  volumeKg: 6420,
  previousPeriodGrowthPercent: 12.4,
  filterOptions: {
    products: [
      "Bispo Especial 500 g",
      "Bispo Clássico 1 kg",
      "Bispo Microlote 250 g",
      "Bispo Essencial 500 g",
    ],
    customers: customers.map((item) => item.name),
    geographies: [
      "Brasil / Sudeste",
      "Brasil / Sul",
      "Europa",
      "América do Norte",
    ],
    channels: ["B2B", "Distribuidores", "E-commerce", "Lojas próprias"],
  },
  products: [
    {
      id: "prod-esp-500",
      product: "Bispo Especial 500 g",
      sku: "BC-ESP-500",
      revenue: 173200,
      volumeKg: 2180,
      target: 180000,
      attainmentPercent: 96.2,
      marginPercent: 24.8,
      profit: 42954,
      growthPercent: 14.2,
      orderCount: 58,
      averagePricePerKg: 79.45,
      averageTicket: 2986,
      closingProjection: 181400,
      trend: [118, 126, 132, 141, 148, 159, 173],
      customers,
      geography: [
        {
          id: "geo-1",
          country: "Brasil",
          region: "Sudeste",
          state: "Minas Gerais",
          city: "Belo Horizonte",
          revenue: 84200,
          sharePercent: 48.6,
        },
        {
          id: "geo-2",
          country: "Brasil",
          region: "Sul",
          state: "Paraná",
          city: "Curitiba",
          revenue: 38600,
          sharePercent: 22.3,
        },
        {
          id: "geo-3",
          country: "Portugal",
          region: "Europa",
          state: "Lisboa",
          city: "Lisboa",
          revenue: 28400,
          sharePercent: 16.4,
        },
      ],
      orders: [
        {
          id: "ped-321",
          code: "PV-2026-0321",
          customer: "Empório Central",
          quantityKg: 120,
          amount: 9576,
          status: "Confirmado",
          orderedAt: "06/08/2026",
        },
        {
          id: "ped-318",
          code: "PV-2026-0318",
          customer: "Rede Grão Nobre",
          quantityKg: 96,
          amount: 7656,
          status: "Em produção",
          orderedAt: "05/08/2026",
        },
      ],
    },
    {
      id: "prod-cla-1k",
      product: "Bispo Clássico 1 kg",
      sku: "BC-CLA-1K",
      revenue: 139400,
      volumeKg: 1640,
      target: 145000,
      attainmentPercent: 96.1,
      marginPercent: 20.3,
      profit: 28298,
      growthPercent: 9.6,
      orderCount: 42,
      averagePricePerKg: 85,
      averageTicket: 3319,
      closingProjection: 146200,
      trend: [96, 101, 108, 112, 119, 128, 139],
      customers,
      geography: [
        {
          id: "geo-4",
          country: "Brasil",
          region: "Sudeste",
          state: "São Paulo",
          city: "São Paulo",
          revenue: 72800,
          sharePercent: 52.2,
        },
      ],
      orders: [
        {
          id: "ped-316",
          code: "PV-2026-0316",
          customer: "Café do Mercado",
          quantityKg: 80,
          amount: 6800,
          status: "Expedição",
          orderedAt: "04/08/2026",
        },
      ],
    },
    {
      id: "prod-mic-250",
      product: "Bispo Microlote 250 g",
      sku: "BC-MIC-250",
      revenue: 92600,
      volumeKg: 980,
      target: 88000,
      attainmentPercent: 105.2,
      marginPercent: 28.1,
      profit: 26021,
      growthPercent: 18.4,
      orderCount: 39,
      averagePricePerKg: 94.49,
      averageTicket: 2374,
      closingProjection: 98700,
      trend: [54, 61, 66, 72, 78, 84, 93],
      customers,
      geography: [
        {
          id: "geo-5",
          country: "Portugal",
          region: "Europa",
          state: "Porto",
          city: "Porto",
          revenue: 31200,
          sharePercent: 33.7,
        },
      ],
      orders: [
        {
          id: "ped-314",
          code: "PV-2026-0314",
          customer: "Empório Central",
          quantityKg: 48,
          amount: 4536,
          status: "Confirmado",
          orderedAt: "03/08/2026",
        },
      ],
    },
    {
      id: "prod-ess-500",
      product: "Bispo Essencial 500 g",
      sku: "BC-ESS-500",
      revenue: 81120,
      volumeKg: 1620,
      target: 101100,
      attainmentPercent: 80.2,
      marginPercent: 14.9,
      profit: 12087,
      growthPercent: -3.1,
      orderCount: 51,
      averagePricePerKg: 50.07,
      averageTicket: 1591,
      closingProjection: 79300,
      trend: [88, 91, 89, 87, 84, 83, 81],
      customers,
      geography: [
        {
          id: "geo-6",
          country: "Brasil",
          region: "Centro-Oeste",
          state: "Goiás",
          city: "Goiânia",
          revenue: 28400,
          sharePercent: 35,
        },
      ],
      orders: [
        {
          id: "ped-309",
          code: "PV-2026-0309",
          customer: "Rede Grão Nobre",
          quantityKg: 140,
          amount: 7000,
          status: "Aguardando",
          orderedAt: "01/08/2026",
        },
      ],
    },
  ],
};
