"use client";

import * as React from "react";
import Link from "next/link";
import { ArrowLeft, CalendarDays, CircleDollarSign, Plus, ReceiptText, X } from "lucide-react";
import { Badge, Card } from "@bbos/ui";

type Payable={id:string;description:string;category:string;issueDate:string;dueDate:string;amount:number|string;openAmount:number|string;status:string;notes?:string|null;supplier?:{name?:string|null}|null;costCenter?:{name?:string|null}|null};
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const categories=["Aluguel","Energia elétrica","Gás","Água","Contabilidade","Funcionários / salários","Encargos trabalhistas","Material de consumo","Manutenção","Segurança","Internet / telefonia","Frete / logística","Impostos e taxas","Serviços terceirizados","Embalagens","Outras despesas"];
const today=()=>new Date().toISOString().slice(0,10);

export default function PayablesPage(){
 const[rows,setRows]=React.useState<Payable[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");const[showNew,setShowNew]=React.useState(false);const[saving,setSaving]=React.useState(false);
 const[form,setForm]=React.useState({description:"",category:"",amount:"",issueDate:today(),dueDate:today(),notes:""});
 const load=React.useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/finance/payables",{credentials:"include",cache:"no-store"});const b=await r.json().catch(()=>[]);if(!r.ok)throw new Error(b?.message??"Não foi possível carregar as despesas.");setRows(Array.isArray(b)?b:[])}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar as despesas.")}finally{setLoading(false)}},[]);
 React.useEffect(()=>{void load()},[load]);
 const create=async()=>{const amount=Number(String(form.amount).replace(",","."));if(!form.description.trim())return setError("Informe uma descrição para a despesa.");if(!form.category)return setError("Escolha uma categoria.");if(!Number.isFinite(amount)||amount<=0)return setError("Informe um valor maior que zero.");setSaving(true);setError("");try{const r=await fetch("/api/finance/payables",{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify({...form,amount})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.message??"Não foi possível lançar a despesa.");setForm({description:"",category:"",amount:"",issueDate:today(),dueDate:today(),notes:""});setShowNew(false);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível lançar a despesa.")}finally{setSaving(false)}};
 const open=rows.filter(r=>!["PAID","CANCELLED"].includes(r.status)).reduce((s,r)=>s+Number(r.openAmount||0),0);const overdue=rows.filter(r=>!["PAID","CANCELLED"].includes(r.status)&&new Date(r.dueDate)<new Date()).reduce((s,r)=>s+Number(r.openAmount||0),0);
 return <div className="mx-auto max-w-[1500px] space-y-6">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/financeiro" className="inline-flex items-center gap-2 text-xs font-bold text-forest-700"><ArrowLeft size={14}/>Financeiro</Link><p className="mt-5 text-[10px] font-bold uppercase tracking-[.16em] text-forest-700">Despesas e compromissos</p><h1 className="mt-1 text-3xl font-bold">Contas a pagar</h1><p className="mt-2 text-sm text-stone-500">Registre despesas reais e acompanhe o impacto no caixa e no resultado.</p></div><button onClick={()=>{setError("");setShowNew(true)}} className="inline-flex items-center gap-2 rounded-xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>Lançar despesa</button></div>
  <div className="grid gap-3 sm:grid-cols-3"><Kpi label="Em aberto" value={money.format(open)}/><Kpi label="Vencido" value={money.format(overdue)} tone={overdue>0?"danger":"neutral"}/><Kpi label="Lançamentos" value={String(rows.length)}/></div>
  {error&&<div className="rounded-xl border border-red-100 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <Card className="overflow-hidden p-0"><div className="hidden grid-cols-7 gap-3 border-b bg-stone-50 p-4 text-[10px] font-bold uppercase tracking-wide text-stone-500 md:grid"><span>Categoria</span><span className="col-span-2">Descrição</span><span>Vencimento</span><span>Valor</span><span>Em aberto</span><span>Status</span></div>{loading?<div className="p-10 text-center text-sm text-stone-500">Carregando compromissos reais…</div>:rows.length===0?<div className="p-12 text-center"><ReceiptText className="mx-auto text-stone-300"/><p className="mt-3 font-semibold">Nenhuma despesa lançada</p><p className="mt-1 text-sm text-stone-500">Comece pelo aluguel, energia, gás, contabilidade ou outra despesa do mês.</p></div>:rows.map(row=>{const isOverdue=!["PAID","CANCELLED"].includes(row.status)&&new Date(row.dueDate)<new Date();return <div key={row.id} className="grid gap-2 border-b border-stone-100 p-4 text-xs md:grid-cols-7 md:items-center"><span className="font-semibold">{row.category}</span><span className="col-span-2"><span className="font-semibold text-stone-800">{row.description}</span>{row.notes&&<span className="mt-1 block text-[11px] text-stone-400">{row.notes}</span>}</span><span>{new Date(row.dueDate).toLocaleDateString("pt-BR")}</span><span>{money.format(Number(row.amount||0))}</span><span className="font-bold">{money.format(Number(row.openAmount||0))}</span><Badge tone={row.status==="PAID"?"success":isOverdue?"danger":"warning"}>{row.status==="PAID"?"Pago":isOverdue?"Vencido":"A pagar"}</Badge></div>})}</Card>
  <div className="rounded-2xl border border-violet-100 bg-violet-50 p-4 text-sm text-violet-900"><strong>BBOS Intelligence</strong><p className="mt-1 text-xs leading-5">Cada despesa lançada passa a alimentar Contas a Pagar e o consolidado financeiro. A próxima evolução será recorrência mensal, centro de custo e apropriação automática à produção quando aplicável.</p></div>
  {showNew&&<div className="fixed inset-0 z-50 flex justify-end bg-black/30"><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.18em] text-violet-700">Novo lançamento</p><h2 className="mt-1 text-2xl font-semibold">Lançar despesa</h2><p className="mt-1 text-sm text-stone-500">Registre o compromisso uma vez; o financeiro passa a enxergá-lo.</p></div><button onClick={()=>setShowNew(false)} className="rounded-xl border p-2"><X size={18}/></button></div><div className="mt-6 space-y-4"><Field label="Descrição"><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Ex.: Aluguel da indústria — setembro"/></Field><Field label="Categoria"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Selecione</option>{categories.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Valor (R$)"><div className="relative"><CircleDollarSign size={16} className="absolute left-3 top-3.5 text-stone-400"/><input className="pl-9" inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></div></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Competência / emissão"><div className="relative"><CalendarDays size={15} className="absolute left-3 top-3.5 text-stone-400"/><input className="pl-9" type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/></div></Field><Field label="Vencimento"><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field></div><Field label="Observações"><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Fornecedor, referência, detalhes do pagamento…"/></Field></div>{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={saving} onClick={()=>void create()} className="mt-6 w-full rounded-xl bg-stone-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Salvando…":"Registrar despesa"}</button></aside></div>}
 </div>}
function Kpi({label,value,tone="neutral"}:{label:string;value:string;tone?:"neutral"|"danger"}){return <Card className="p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-stone-400">{label}</p><p className={`mt-2 text-xl font-bold ${tone==="danger"?"text-red-700":"text-stone-900"}`}>{value}</p></Card>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-semibold text-stone-700"><span>{label}</span><div className="mt-1 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:px-3 [&_input]:py-3 [&_select]:w-full [&_select]:rounded-xl [&_select]:border [&_select]:px-3 [&_select]:py-3 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:px-3 [&_textarea]:py-3 [&_input]:outline-none [&_select]:outline-none [&_textarea]:outline-none">{children}</div></label>}
